[2025-02-21T09:40:47.428+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: optum_etl_file_dag3.transform_task scheduled__2025-02-08T00:00:00+00:00 [queued]>
[2025-02-21T09:40:47.469+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: optum_etl_file_dag3.transform_task scheduled__2025-02-08T00:00:00+00:00 [queued]>
[2025-02-21T09:40:47.472+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-02-21T09:40:47.528+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): transform_task> on 2025-02-08 00:00:00+00:00
[2025-02-21T09:40:47.602+0000] {standard_task_runner.py:60} INFO - Started process 5794 to run task
[2025-02-21T09:40:47.617+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'optum_etl_file_dag3', 'transform_task', 'scheduled__2025-02-08T00:00:00+00:00', '--job-id', '1038', '--raw', '--subdir', 'DAGS_FOLDER/optum_file_dag3.py', '--cfg-path', '/tmp/tmplm18fmm8']
[2025-02-21T09:40:47.623+0000] {standard_task_runner.py:88} INFO - Job 1038: Subtask transform_task
[2025-02-21T09:40:48.133+0000] {task_command.py:423} INFO - Running <TaskInstance: optum_etl_file_dag3.transform_task scheduled__2025-02-08T00:00:00+00:00 [running]> on host 491940227afd
[2025-02-21T09:40:48.978+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='optum_etl_file_dag3' AIRFLOW_CTX_TASK_ID='transform_task' AIRFLOW_CTX_EXECUTION_DATE='2025-02-08T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-02-08T00:00:00+00:00'
[2025-02-21T09:40:48.986+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-02-21T09:40:49.015+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=optum_etl_file_dag3, task_id=transform_task, execution_date=20250208T000000, start_date=20250221T094047, end_date=20250221T094049
[2025-02-21T09:40:49.148+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-02-21T09:40:49.221+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
