[2025-02-21T09:40:22.638+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: optum_etl_file_dag3.transform_task scheduled__2025-02-02T00:00:00+00:00 [queued]>
[2025-02-21T09:40:22.661+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: optum_etl_file_dag3.transform_task scheduled__2025-02-02T00:00:00+00:00 [queued]>
[2025-02-21T09:40:22.662+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-02-21T09:40:22.699+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): transform_task> on 2025-02-02 00:00:00+00:00
[2025-02-21T09:40:22.751+0000] {standard_task_runner.py:60} INFO - Started process 5713 to run task
[2025-02-21T09:40:22.809+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'optum_etl_file_dag3', 'transform_task', 'scheduled__2025-02-02T00:00:00+00:00', '--job-id', '1017', '--raw', '--subdir', 'DAGS_FOLDER/optum_file_dag3.py', '--cfg-path', '/tmp/tmp0n4kbp_j']
[2025-02-21T09:40:22.842+0000] {standard_task_runner.py:88} INFO - Job 1017: Subtask transform_task
[2025-02-21T09:40:23.180+0000] {task_command.py:423} INFO - Running <TaskInstance: optum_etl_file_dag3.transform_task scheduled__2025-02-02T00:00:00+00:00 [running]> on host 491940227afd
[2025-02-21T09:40:23.673+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='optum_etl_file_dag3' AIRFLOW_CTX_TASK_ID='transform_task' AIRFLOW_CTX_EXECUTION_DATE='2025-02-02T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-02-02T00:00:00+00:00'
[2025-02-21T09:40:23.693+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-02-21T09:40:23.734+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=optum_etl_file_dag3, task_id=transform_task, execution_date=20250202T000000, start_date=20250221T094022, end_date=20250221T094023
[2025-02-21T09:40:23.836+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-02-21T09:40:24.062+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
