[2025-02-21T09:40:52.126+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: optum_etl_file_dag3.transform_task scheduled__2025-02-11T00:00:00+00:00 [queued]>
[2025-02-21T09:40:52.167+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: optum_etl_file_dag3.transform_task scheduled__2025-02-11T00:00:00+00:00 [queued]>
[2025-02-21T09:40:52.168+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-02-21T09:40:52.276+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): transform_task> on 2025-02-11 00:00:00+00:00
[2025-02-21T09:40:52.308+0000] {standard_task_runner.py:60} INFO - Started process 5812 to run task
[2025-02-21T09:40:52.468+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'optum_etl_file_dag3', 'transform_task', 'scheduled__2025-02-11T00:00:00+00:00', '--job-id', '1044', '--raw', '--subdir', 'DAGS_FOLDER/optum_file_dag3.py', '--cfg-path', '/tmp/tmpjue_kaja']
[2025-02-21T09:40:52.486+0000] {standard_task_runner.py:88} INFO - Job 1044: Subtask transform_task
[2025-02-21T09:40:52.793+0000] {task_command.py:423} INFO - Running <TaskInstance: optum_etl_file_dag3.transform_task scheduled__2025-02-11T00:00:00+00:00 [running]> on host 491940227afd
[2025-02-21T09:40:53.256+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='optum_etl_file_dag3' AIRFLOW_CTX_TASK_ID='transform_task' AIRFLOW_CTX_EXECUTION_DATE='2025-02-11T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-02-11T00:00:00+00:00'
[2025-02-21T09:40:53.274+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-02-21T09:40:53.312+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=optum_etl_file_dag3, task_id=transform_task, execution_date=20250211T000000, start_date=20250221T094052, end_date=20250221T094053
[2025-02-21T09:40:53.463+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-02-21T09:40:53.536+0000] {taskinstance.py:3280} INFO - 1 downstream tasks scheduled from follow-on schedule check
