[2025-02-21T09:40:47.082+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: optum_etl_file_dag3.transform_task scheduled__2025-02-06T00:00:00+00:00 [queued]>
[2025-02-21T09:40:47.106+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: optum_etl_file_dag3.transform_task scheduled__2025-02-06T00:00:00+00:00 [queued]>
[2025-02-21T09:40:47.108+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-02-21T09:40:47.152+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): transform_task> on 2025-02-06 00:00:00+00:00
[2025-02-21T09:40:47.181+0000] {standard_task_runner.py:60} INFO - Started process 5791 to run task
[2025-02-21T09:40:47.219+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'optum_etl_file_dag3', 'transform_task', 'scheduled__2025-02-06T00:00:00+00:00', '--job-id', '1037', '--raw', '--subdir', 'DAGS_FOLDER/optum_file_dag3.py', '--cfg-path', '/tmp/tmpd04rc0hm']
[2025-02-21T09:40:47.230+0000] {standard_task_runner.py:88} INFO - Job 1037: Subtask transform_task
[2025-02-21T09:40:47.402+0000] {task_command.py:423} INFO - Running <TaskInstance: optum_etl_file_dag3.transform_task scheduled__2025-02-06T00:00:00+00:00 [running]> on host 491940227afd
[2025-02-21T09:40:47.844+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='optum_etl_file_dag3' AIRFLOW_CTX_TASK_ID='transform_task' AIRFLOW_CTX_EXECUTION_DATE='2025-02-06T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-02-06T00:00:00+00:00'
[2025-02-21T09:40:47.870+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-02-21T09:40:47.939+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=optum_etl_file_dag3, task_id=transform_task, execution_date=20250206T000000, start_date=20250221T094047, end_date=20250221T094047
[2025-02-21T09:40:48.254+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-02-21T09:40:48.371+0000] {taskinstance.py:3280} INFO - 1 downstream tasks scheduled from follow-on schedule check
