[2025-02-21T09:40:09.039+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: optum_etl_file_dag3.transform_task scheduled__2025-02-01T00:00:00+00:00 [queued]>
[2025-02-21T09:40:09.121+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: optum_etl_file_dag3.transform_task scheduled__2025-02-01T00:00:00+00:00 [queued]>
[2025-02-21T09:40:09.158+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-02-21T09:40:09.291+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): transform_task> on 2025-02-01 00:00:00+00:00
[2025-02-21T09:40:09.380+0000] {standard_task_runner.py:60} INFO - Started process 5682 to run task
[2025-02-21T09:40:09.384+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'optum_etl_file_dag3', 'transform_task', 'scheduled__2025-02-01T00:00:00+00:00', '--job-id', '1004', '--raw', '--subdir', 'DAGS_FOLDER/optum_file_dag3.py', '--cfg-path', '/tmp/tmpykitpj3t']
[2025-02-21T09:40:09.450+0000] {standard_task_runner.py:88} INFO - Job 1004: Subtask transform_task
[2025-02-21T09:40:09.927+0000] {task_command.py:423} INFO - Running <TaskInstance: optum_etl_file_dag3.transform_task scheduled__2025-02-01T00:00:00+00:00 [running]> on host 491940227afd
[2025-02-21T09:40:10.522+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='optum_etl_file_dag3' AIRFLOW_CTX_TASK_ID='transform_task' AIRFLOW_CTX_EXECUTION_DATE='2025-02-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-02-01T00:00:00+00:00'
[2025-02-21T09:40:10.532+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-02-21T09:40:10.587+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=optum_etl_file_dag3, task_id=transform_task, execution_date=20250201T000000, start_date=20250221T094009, end_date=20250221T094010
[2025-02-21T09:40:10.806+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-02-21T09:40:10.902+0000] {taskinstance.py:3280} INFO - 1 downstream tasks scheduled from follow-on schedule check
