[2025-02-21T07:57:58.344+0000] {processor.py:161} INFO - Started process (PID=11500) to work on /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T07:57:58.348+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/optum_ml_dag.py for tasks to queue
[2025-02-21T07:57:58.352+0000] {logging_mixin.py:188} INFO - [2025-02-21T07:57:58.351+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T07:57:59.279+0000] {logging_mixin.py:188} INFO - [2025-02-21T07:57:59.256+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/optum_ml_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/optum_ml_dag.py", line 7, in <module>
    from sklearn.ensemble import RandomForestClassifier
ModuleNotFoundError: No module named 'sklearn'
[2025-02-21T07:57:59.284+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T07:57:59.344+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/optum_ml_dag.py took 1.014 seconds
[2025-02-21T07:58:29.964+0000] {processor.py:161} INFO - Started process (PID=11563) to work on /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T07:58:29.968+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/optum_ml_dag.py for tasks to queue
[2025-02-21T07:58:29.971+0000] {logging_mixin.py:188} INFO - [2025-02-21T07:58:29.970+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T07:58:30.806+0000] {logging_mixin.py:188} INFO - [2025-02-21T07:58:30.792+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/optum_ml_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/optum_ml_dag.py", line 7, in <module>
    from sklearn.ensemble import RandomForestClassifier
ModuleNotFoundError: No module named 'sklearn'
[2025-02-21T07:58:30.811+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T07:58:30.859+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/optum_ml_dag.py took 0.926 seconds
[2025-02-21T07:59:01.096+0000] {processor.py:161} INFO - Started process (PID=11627) to work on /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T07:59:01.101+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/optum_ml_dag.py for tasks to queue
[2025-02-21T07:59:01.105+0000] {logging_mixin.py:188} INFO - [2025-02-21T07:59:01.104+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T07:59:02.281+0000] {logging_mixin.py:188} INFO - [2025-02-21T07:59:02.241+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/optum_ml_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/optum_ml_dag.py", line 7, in <module>
    from sklearn.ensemble import RandomForestClassifier
ModuleNotFoundError: No module named 'sklearn'
[2025-02-21T07:59:02.292+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T07:59:02.400+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/optum_ml_dag.py took 1.324 seconds
[2025-02-21T07:59:33.090+0000] {processor.py:161} INFO - Started process (PID=11690) to work on /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T07:59:33.096+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/optum_ml_dag.py for tasks to queue
[2025-02-21T07:59:33.102+0000] {logging_mixin.py:188} INFO - [2025-02-21T07:59:33.100+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T07:59:34.072+0000] {logging_mixin.py:188} INFO - [2025-02-21T07:59:34.037+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/optum_ml_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/optum_ml_dag.py", line 7, in <module>
    from sklearn.ensemble import RandomForestClassifier
ModuleNotFoundError: No module named 'sklearn'
[2025-02-21T07:59:34.081+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T07:59:34.154+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/optum_ml_dag.py took 1.084 seconds
[2025-02-21T08:00:05.767+0000] {processor.py:161} INFO - Started process (PID=11756) to work on /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:00:05.770+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/optum_ml_dag.py for tasks to queue
[2025-02-21T08:00:05.774+0000] {logging_mixin.py:188} INFO - [2025-02-21T08:00:05.773+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:00:07.015+0000] {logging_mixin.py:188} INFO - [2025-02-21T08:00:06.965+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/optum_ml_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/optum_ml_dag.py", line 7, in <module>
    from sklearn.ensemble import RandomForestClassifier
ModuleNotFoundError: No module named 'sklearn'
[2025-02-21T08:00:07.020+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:00:07.111+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/optum_ml_dag.py took 1.359 seconds
[2025-02-21T08:00:37.812+0000] {processor.py:161} INFO - Started process (PID=11820) to work on /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:00:37.818+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/optum_ml_dag.py for tasks to queue
[2025-02-21T08:00:37.822+0000] {logging_mixin.py:188} INFO - [2025-02-21T08:00:37.821+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:00:38.702+0000] {logging_mixin.py:188} INFO - [2025-02-21T08:00:38.684+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/optum_ml_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/optum_ml_dag.py", line 7, in <module>
    from sklearn.ensemble import RandomForestClassifier
ModuleNotFoundError: No module named 'sklearn'
[2025-02-21T08:00:38.708+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:00:38.771+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/optum_ml_dag.py took 0.967 seconds
[2025-02-21T08:01:09.501+0000] {processor.py:161} INFO - Started process (PID=11884) to work on /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:01:09.506+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/optum_ml_dag.py for tasks to queue
[2025-02-21T08:01:09.511+0000] {logging_mixin.py:188} INFO - [2025-02-21T08:01:09.509+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:01:10.460+0000] {logging_mixin.py:188} INFO - [2025-02-21T08:01:10.430+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/optum_ml_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/optum_ml_dag.py", line 7, in <module>
    from sklearn.ensemble import RandomForestClassifier
ModuleNotFoundError: No module named 'sklearn'
[2025-02-21T08:01:10.474+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:01:10.553+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/optum_ml_dag.py took 1.069 seconds
[2025-02-21T08:01:41.057+0000] {processor.py:161} INFO - Started process (PID=11949) to work on /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:01:41.066+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/optum_ml_dag.py for tasks to queue
[2025-02-21T08:01:41.072+0000] {logging_mixin.py:188} INFO - [2025-02-21T08:01:41.071+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:01:42.087+0000] {logging_mixin.py:188} INFO - [2025-02-21T08:01:42.068+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/optum_ml_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/optum_ml_dag.py", line 7, in <module>
    from sklearn.ensemble import RandomForestClassifier
ModuleNotFoundError: No module named 'sklearn'
[2025-02-21T08:01:42.093+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:01:42.147+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/optum_ml_dag.py took 1.108 seconds
[2025-02-21T08:02:12.606+0000] {processor.py:161} INFO - Started process (PID=12014) to work on /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:02:12.610+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/optum_ml_dag.py for tasks to queue
[2025-02-21T08:02:12.612+0000] {logging_mixin.py:188} INFO - [2025-02-21T08:02:12.612+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:02:13.689+0000] {logging_mixin.py:188} INFO - [2025-02-21T08:02:13.663+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/optum_ml_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/optum_ml_dag.py", line 7, in <module>
    from sklearn.ensemble import RandomForestClassifier
ModuleNotFoundError: No module named 'sklearn'
[2025-02-21T08:02:13.694+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:02:13.759+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/optum_ml_dag.py took 1.165 seconds
[2025-02-21T08:02:43.970+0000] {processor.py:161} INFO - Started process (PID=12078) to work on /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:02:43.975+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/optum_ml_dag.py for tasks to queue
[2025-02-21T08:02:43.979+0000] {logging_mixin.py:188} INFO - [2025-02-21T08:02:43.978+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:02:44.781+0000] {logging_mixin.py:188} INFO - [2025-02-21T08:02:44.766+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/optum_ml_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/optum_ml_dag.py", line 7, in <module>
    from sklearn.ensemble import RandomForestClassifier
ModuleNotFoundError: No module named 'sklearn'
[2025-02-21T08:02:44.786+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:02:44.842+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/optum_ml_dag.py took 0.887 seconds
[2025-02-21T08:03:15.221+0000] {processor.py:161} INFO - Started process (PID=12143) to work on /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:03:15.224+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/optum_ml_dag.py for tasks to queue
[2025-02-21T08:03:15.227+0000] {logging_mixin.py:188} INFO - [2025-02-21T08:03:15.226+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:03:15.935+0000] {logging_mixin.py:188} INFO - [2025-02-21T08:03:15.922+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/optum_ml_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/optum_ml_dag.py", line 7, in <module>
    from sklearn.ensemble import RandomForestClassifier
ModuleNotFoundError: No module named 'sklearn'
[2025-02-21T08:03:15.939+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:03:15.991+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/optum_ml_dag.py took 0.781 seconds
[2025-02-21T08:03:46.467+0000] {processor.py:161} INFO - Started process (PID=12206) to work on /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:03:46.473+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/optum_ml_dag.py for tasks to queue
[2025-02-21T08:03:46.477+0000] {logging_mixin.py:188} INFO - [2025-02-21T08:03:46.476+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:03:47.592+0000] {logging_mixin.py:188} INFO - [2025-02-21T08:03:47.564+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/optum_ml_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/optum_ml_dag.py", line 7, in <module>
    from sklearn.ensemble import RandomForestClassifier
ModuleNotFoundError: No module named 'sklearn'
[2025-02-21T08:03:47.596+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:03:47.673+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/optum_ml_dag.py took 1.218 seconds
[2025-02-21T08:04:18.307+0000] {processor.py:161} INFO - Started process (PID=12270) to work on /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:04:18.311+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/optum_ml_dag.py for tasks to queue
[2025-02-21T08:04:18.315+0000] {logging_mixin.py:188} INFO - [2025-02-21T08:04:18.314+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:04:19.200+0000] {logging_mixin.py:188} INFO - [2025-02-21T08:04:19.163+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/optum_ml_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/optum_ml_dag.py", line 7, in <module>
    from sklearn.ensemble import RandomForestClassifier
ModuleNotFoundError: No module named 'sklearn'
[2025-02-21T08:04:19.210+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:04:19.271+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/optum_ml_dag.py took 0.977 seconds
[2025-02-21T08:04:49.478+0000] {processor.py:161} INFO - Started process (PID=12334) to work on /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:04:49.483+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/optum_ml_dag.py for tasks to queue
[2025-02-21T08:04:49.487+0000] {logging_mixin.py:188} INFO - [2025-02-21T08:04:49.486+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:04:50.405+0000] {logging_mixin.py:188} INFO - [2025-02-21T08:04:50.374+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/optum_ml_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/optum_ml_dag.py", line 7, in <module>
    from sklearn.ensemble import RandomForestClassifier
ModuleNotFoundError: No module named 'sklearn'
[2025-02-21T08:04:50.422+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:04:50.484+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/optum_ml_dag.py took 1.022 seconds
[2025-02-21T08:05:21.057+0000] {processor.py:161} INFO - Started process (PID=12398) to work on /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:05:21.067+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/optum_ml_dag.py for tasks to queue
[2025-02-21T08:05:21.088+0000] {logging_mixin.py:188} INFO - [2025-02-21T08:05:21.086+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:05:22.164+0000] {logging_mixin.py:188} INFO - [2025-02-21T08:05:22.147+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/optum_ml_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/optum_ml_dag.py", line 7, in <module>
    from sklearn.ensemble import RandomForestClassifier
ModuleNotFoundError: No module named 'sklearn'
[2025-02-21T08:05:22.168+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:05:22.224+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/optum_ml_dag.py took 1.189 seconds
[2025-02-21T08:05:52.588+0000] {processor.py:161} INFO - Started process (PID=12461) to work on /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:05:52.592+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/optum_ml_dag.py for tasks to queue
[2025-02-21T08:05:52.596+0000] {logging_mixin.py:188} INFO - [2025-02-21T08:05:52.595+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:05:53.634+0000] {logging_mixin.py:188} INFO - [2025-02-21T08:05:53.612+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/optum_ml_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/optum_ml_dag.py", line 7, in <module>
    from sklearn.ensemble import RandomForestClassifier
ModuleNotFoundError: No module named 'sklearn'
[2025-02-21T08:05:53.641+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:05:53.709+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/optum_ml_dag.py took 1.130 seconds
[2025-02-21T08:06:24.161+0000] {processor.py:161} INFO - Started process (PID=12527) to work on /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:06:24.164+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/optum_ml_dag.py for tasks to queue
[2025-02-21T08:06:24.166+0000] {logging_mixin.py:188} INFO - [2025-02-21T08:06:24.165+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:06:25.064+0000] {logging_mixin.py:188} INFO - [2025-02-21T08:06:25.041+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/optum_ml_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/optum_ml_dag.py", line 7, in <module>
    from sklearn.ensemble import RandomForestClassifier
ModuleNotFoundError: No module named 'sklearn'
[2025-02-21T08:06:25.070+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:06:25.126+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/optum_ml_dag.py took 0.974 seconds
[2025-02-21T08:06:55.570+0000] {processor.py:161} INFO - Started process (PID=12596) to work on /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:06:55.574+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/optum_ml_dag.py for tasks to queue
[2025-02-21T08:06:55.577+0000] {logging_mixin.py:188} INFO - [2025-02-21T08:06:55.576+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:06:56.338+0000] {logging_mixin.py:188} INFO - [2025-02-21T08:06:56.322+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/optum_ml_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/optum_ml_dag.py", line 7, in <module>
    from sklearn.ensemble import RandomForestClassifier
ModuleNotFoundError: No module named 'sklearn'
[2025-02-21T08:06:56.344+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:06:56.399+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/optum_ml_dag.py took 0.840 seconds
[2025-02-21T08:07:27.212+0000] {processor.py:161} INFO - Started process (PID=12663) to work on /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:07:27.216+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/optum_ml_dag.py for tasks to queue
[2025-02-21T08:07:27.224+0000] {logging_mixin.py:188} INFO - [2025-02-21T08:07:27.222+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:07:28.156+0000] {logging_mixin.py:188} INFO - [2025-02-21T08:07:28.137+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/optum_ml_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/optum_ml_dag.py", line 7, in <module>
    from sklearn.ensemble import RandomForestClassifier
ModuleNotFoundError: No module named 'sklearn'
[2025-02-21T08:07:28.164+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:07:28.232+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/optum_ml_dag.py took 1.031 seconds
[2025-02-21T08:07:58.628+0000] {processor.py:161} INFO - Started process (PID=12725) to work on /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:07:58.632+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/optum_ml_dag.py for tasks to queue
[2025-02-21T08:07:58.637+0000] {logging_mixin.py:188} INFO - [2025-02-21T08:07:58.636+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:07:59.705+0000] {logging_mixin.py:188} INFO - [2025-02-21T08:07:59.687+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/optum_ml_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/optum_ml_dag.py", line 7, in <module>
    from sklearn.ensemble import RandomForestClassifier
ModuleNotFoundError: No module named 'sklearn'
[2025-02-21T08:07:59.711+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:07:59.782+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/optum_ml_dag.py took 1.166 seconds
[2025-02-21T08:08:30.170+0000] {processor.py:161} INFO - Started process (PID=12788) to work on /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:08:30.174+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/optum_ml_dag.py for tasks to queue
[2025-02-21T08:08:30.177+0000] {logging_mixin.py:188} INFO - [2025-02-21T08:08:30.176+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:08:31.069+0000] {logging_mixin.py:188} INFO - [2025-02-21T08:08:31.049+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/optum_ml_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/optum_ml_dag.py", line 7, in <module>
    from sklearn.ensemble import RandomForestClassifier
ModuleNotFoundError: No module named 'sklearn'
[2025-02-21T08:08:31.076+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:08:31.136+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/optum_ml_dag.py took 0.975 seconds
[2025-02-21T08:09:01.621+0000] {processor.py:161} INFO - Started process (PID=12850) to work on /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:09:01.625+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/optum_ml_dag.py for tasks to queue
[2025-02-21T08:09:01.629+0000] {logging_mixin.py:188} INFO - [2025-02-21T08:09:01.628+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:09:02.629+0000] {logging_mixin.py:188} INFO - [2025-02-21T08:09:02.615+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/optum_ml_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/optum_ml_dag.py", line 7, in <module>
    from sklearn.ensemble import RandomForestClassifier
ModuleNotFoundError: No module named 'sklearn'
[2025-02-21T08:09:02.634+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:09:02.696+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/optum_ml_dag.py took 1.086 seconds
[2025-02-21T08:09:33.626+0000] {processor.py:161} INFO - Started process (PID=12914) to work on /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:09:33.634+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/optum_ml_dag.py for tasks to queue
[2025-02-21T08:09:33.650+0000] {logging_mixin.py:188} INFO - [2025-02-21T08:09:33.649+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:09:34.789+0000] {logging_mixin.py:188} INFO - [2025-02-21T08:09:34.777+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/optum_ml_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/optum_ml_dag.py", line 7, in <module>
    from sklearn.ensemble import RandomForestClassifier
ModuleNotFoundError: No module named 'sklearn'
[2025-02-21T08:09:34.793+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:09:34.842+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/optum_ml_dag.py took 1.269 seconds
[2025-02-21T08:10:05.433+0000] {processor.py:161} INFO - Started process (PID=12977) to work on /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:10:05.436+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/optum_ml_dag.py for tasks to queue
[2025-02-21T08:10:05.439+0000] {logging_mixin.py:188} INFO - [2025-02-21T08:10:05.438+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:10:06.375+0000] {logging_mixin.py:188} INFO - [2025-02-21T08:10:06.360+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/optum_ml_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/optum_ml_dag.py", line 7, in <module>
    from sklearn.ensemble import RandomForestClassifier
ModuleNotFoundError: No module named 'sklearn'
[2025-02-21T08:10:06.381+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:10:06.429+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/optum_ml_dag.py took 1.007 seconds
[2025-02-21T08:10:36.685+0000] {processor.py:161} INFO - Started process (PID=13042) to work on /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:10:36.688+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/optum_ml_dag.py for tasks to queue
[2025-02-21T08:10:36.691+0000] {logging_mixin.py:188} INFO - [2025-02-21T08:10:36.690+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:10:37.726+0000] {logging_mixin.py:188} INFO - [2025-02-21T08:10:37.698+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/optum_ml_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/optum_ml_dag.py", line 7, in <module>
    from sklearn.ensemble import RandomForestClassifier
ModuleNotFoundError: No module named 'sklearn'
[2025-02-21T08:10:37.732+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:10:37.800+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/optum_ml_dag.py took 1.123 seconds
[2025-02-21T08:11:08.506+0000] {processor.py:161} INFO - Started process (PID=13106) to work on /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:11:08.509+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/optum_ml_dag.py for tasks to queue
[2025-02-21T08:11:08.512+0000] {logging_mixin.py:188} INFO - [2025-02-21T08:11:08.512+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:11:09.436+0000] {logging_mixin.py:188} INFO - [2025-02-21T08:11:09.410+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/optum_ml_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/optum_ml_dag.py", line 7, in <module>
    from sklearn.ensemble import RandomForestClassifier
ModuleNotFoundError: No module named 'sklearn'
[2025-02-21T08:11:09.444+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:11:09.498+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/optum_ml_dag.py took 1.000 seconds
[2025-02-21T08:11:40.127+0000] {processor.py:161} INFO - Started process (PID=13171) to work on /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:11:40.130+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/optum_ml_dag.py for tasks to queue
[2025-02-21T08:11:40.137+0000] {logging_mixin.py:188} INFO - [2025-02-21T08:11:40.135+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:11:41.064+0000] {logging_mixin.py:188} INFO - [2025-02-21T08:11:41.036+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/optum_ml_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/optum_ml_dag.py", line 7, in <module>
    from sklearn.ensemble import RandomForestClassifier
ModuleNotFoundError: No module named 'sklearn'
[2025-02-21T08:11:41.076+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:11:41.149+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/optum_ml_dag.py took 1.033 seconds
[2025-02-21T08:12:11.458+0000] {processor.py:161} INFO - Started process (PID=13236) to work on /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:12:11.462+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/optum_ml_dag.py for tasks to queue
[2025-02-21T08:12:11.467+0000] {logging_mixin.py:188} INFO - [2025-02-21T08:12:11.466+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:12:12.435+0000] {logging_mixin.py:188} INFO - [2025-02-21T08:12:12.413+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/optum_ml_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/optum_ml_dag.py", line 7, in <module>
    from sklearn.ensemble import RandomForestClassifier
ModuleNotFoundError: No module named 'sklearn'
[2025-02-21T08:12:12.446+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:12:12.516+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/optum_ml_dag.py took 1.069 seconds
[2025-02-21T08:12:43.218+0000] {processor.py:161} INFO - Started process (PID=13300) to work on /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:12:43.221+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/optum_ml_dag.py for tasks to queue
[2025-02-21T08:12:43.225+0000] {logging_mixin.py:188} INFO - [2025-02-21T08:12:43.224+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:12:44.288+0000] {logging_mixin.py:188} INFO - [2025-02-21T08:12:44.268+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/optum_ml_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/optum_ml_dag.py", line 7, in <module>
    from sklearn.ensemble import RandomForestClassifier
ModuleNotFoundError: No module named 'sklearn'
[2025-02-21T08:12:44.294+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:12:44.359+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/optum_ml_dag.py took 1.161 seconds
[2025-02-21T08:13:14.706+0000] {processor.py:161} INFO - Started process (PID=13365) to work on /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:13:14.709+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/optum_ml_dag.py for tasks to queue
[2025-02-21T08:13:14.712+0000] {logging_mixin.py:188} INFO - [2025-02-21T08:13:14.711+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:13:15.428+0000] {logging_mixin.py:188} INFO - [2025-02-21T08:13:15.413+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/optum_ml_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/optum_ml_dag.py", line 7, in <module>
    from sklearn.ensemble import RandomForestClassifier
ModuleNotFoundError: No module named 'sklearn'
[2025-02-21T08:13:15.433+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:13:15.486+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/optum_ml_dag.py took 0.792 seconds
[2025-02-21T08:13:45.897+0000] {processor.py:161} INFO - Started process (PID=13430) to work on /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:13:45.903+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/optum_ml_dag.py for tasks to queue
[2025-02-21T08:13:45.905+0000] {logging_mixin.py:188} INFO - [2025-02-21T08:13:45.905+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:13:46.977+0000] {logging_mixin.py:188} INFO - [2025-02-21T08:13:46.938+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/optum_ml_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/optum_ml_dag.py", line 7, in <module>
    from sklearn.ensemble import RandomForestClassifier
ModuleNotFoundError: No module named 'sklearn'
[2025-02-21T08:13:46.986+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:13:47.053+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/optum_ml_dag.py took 1.168 seconds
[2025-02-21T08:14:17.569+0000] {processor.py:161} INFO - Started process (PID=13494) to work on /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:14:17.575+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/optum_ml_dag.py for tasks to queue
[2025-02-21T08:14:17.581+0000] {logging_mixin.py:188} INFO - [2025-02-21T08:14:17.580+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:14:18.631+0000] {logging_mixin.py:188} INFO - [2025-02-21T08:14:18.611+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/optum_ml_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/optum_ml_dag.py", line 7, in <module>
    from sklearn.ensemble import RandomForestClassifier
ModuleNotFoundError: No module named 'sklearn'
[2025-02-21T08:14:18.634+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:14:18.679+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/optum_ml_dag.py took 1.125 seconds
[2025-02-21T08:14:49.076+0000] {processor.py:161} INFO - Started process (PID=13559) to work on /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:14:49.080+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/optum_ml_dag.py for tasks to queue
[2025-02-21T08:14:49.083+0000] {logging_mixin.py:188} INFO - [2025-02-21T08:14:49.083+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:14:50.000+0000] {logging_mixin.py:188} INFO - [2025-02-21T08:14:49.970+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/optum_ml_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/optum_ml_dag.py", line 7, in <module>
    from sklearn.ensemble import RandomForestClassifier
ModuleNotFoundError: No module named 'sklearn'
[2025-02-21T08:14:50.014+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:14:50.073+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/optum_ml_dag.py took 1.009 seconds
[2025-02-21T08:15:20.649+0000] {processor.py:161} INFO - Started process (PID=13623) to work on /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:15:20.654+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/optum_ml_dag.py for tasks to queue
[2025-02-21T08:15:20.678+0000] {logging_mixin.py:188} INFO - [2025-02-21T08:15:20.677+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:15:21.699+0000] {logging_mixin.py:188} INFO - [2025-02-21T08:15:21.683+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/optum_ml_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/optum_ml_dag.py", line 7, in <module>
    from sklearn.ensemble import RandomForestClassifier
ModuleNotFoundError: No module named 'sklearn'
[2025-02-21T08:15:21.705+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:15:21.760+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/optum_ml_dag.py took 1.127 seconds
[2025-02-21T08:15:52.050+0000] {processor.py:161} INFO - Started process (PID=13688) to work on /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:15:52.055+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/optum_ml_dag.py for tasks to queue
[2025-02-21T08:15:52.059+0000] {logging_mixin.py:188} INFO - [2025-02-21T08:15:52.058+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:15:53.009+0000] {logging_mixin.py:188} INFO - [2025-02-21T08:15:52.980+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/optum_ml_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/optum_ml_dag.py", line 7, in <module>
    from sklearn.ensemble import RandomForestClassifier
ModuleNotFoundError: No module named 'sklearn'
[2025-02-21T08:15:53.016+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:15:53.089+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/optum_ml_dag.py took 1.051 seconds
[2025-02-21T08:16:24.037+0000] {processor.py:161} INFO - Started process (PID=13750) to work on /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:16:24.041+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/optum_ml_dag.py for tasks to queue
[2025-02-21T08:16:24.046+0000] {logging_mixin.py:188} INFO - [2025-02-21T08:16:24.045+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:16:24.938+0000] {logging_mixin.py:188} INFO - [2025-02-21T08:16:24.920+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/optum_ml_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/optum_ml_dag.py", line 7, in <module>
    from sklearn.ensemble import RandomForestClassifier
ModuleNotFoundError: No module named 'sklearn'
[2025-02-21T08:16:24.944+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:16:24.992+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/optum_ml_dag.py took 0.968 seconds
[2025-02-21T08:16:55.744+0000] {processor.py:161} INFO - Started process (PID=13815) to work on /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:16:55.748+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/optum_ml_dag.py for tasks to queue
[2025-02-21T08:16:55.751+0000] {logging_mixin.py:188} INFO - [2025-02-21T08:16:55.750+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:16:56.542+0000] {logging_mixin.py:188} INFO - [2025-02-21T08:16:56.515+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/optum_ml_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/optum_ml_dag.py", line 7, in <module>
    from sklearn.ensemble import RandomForestClassifier
ModuleNotFoundError: No module named 'sklearn'
[2025-02-21T08:16:56.551+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:16:56.640+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/optum_ml_dag.py took 0.907 seconds
[2025-02-21T08:17:27.191+0000] {processor.py:161} INFO - Started process (PID=13879) to work on /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:17:27.194+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/optum_ml_dag.py for tasks to queue
[2025-02-21T08:17:27.196+0000] {logging_mixin.py:188} INFO - [2025-02-21T08:17:27.195+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:17:28.362+0000] {logging_mixin.py:188} INFO - [2025-02-21T08:17:28.339+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/optum_ml_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/optum_ml_dag.py", line 7, in <module>
    from sklearn.ensemble import RandomForestClassifier
ModuleNotFoundError: No module named 'sklearn'
[2025-02-21T08:17:28.368+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:17:28.445+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/optum_ml_dag.py took 1.264 seconds
[2025-02-21T08:17:58.971+0000] {processor.py:161} INFO - Started process (PID=13942) to work on /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:17:58.975+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/optum_ml_dag.py for tasks to queue
[2025-02-21T08:17:58.977+0000] {logging_mixin.py:188} INFO - [2025-02-21T08:17:58.977+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:18:00.089+0000] {logging_mixin.py:188} INFO - [2025-02-21T08:18:00.064+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/optum_ml_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/optum_ml_dag.py", line 7, in <module>
    from sklearn.ensemble import RandomForestClassifier
ModuleNotFoundError: No module named 'sklearn'
[2025-02-21T08:18:00.096+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:18:00.177+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/optum_ml_dag.py took 1.216 seconds
[2025-02-21T08:18:30.609+0000] {processor.py:161} INFO - Started process (PID=14012) to work on /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:18:30.612+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/optum_ml_dag.py for tasks to queue
[2025-02-21T08:18:30.616+0000] {logging_mixin.py:188} INFO - [2025-02-21T08:18:30.615+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:18:31.595+0000] {logging_mixin.py:188} INFO - [2025-02-21T08:18:31.548+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/optum_ml_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/optum_ml_dag.py", line 7, in <module>
    from sklearn.ensemble import RandomForestClassifier
ModuleNotFoundError: No module named 'sklearn'
[2025-02-21T08:18:31.602+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:18:31.699+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/optum_ml_dag.py took 1.100 seconds
[2025-02-21T08:19:01.911+0000] {processor.py:161} INFO - Started process (PID=14075) to work on /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:19:01.936+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/optum_ml_dag.py for tasks to queue
[2025-02-21T08:19:01.949+0000] {logging_mixin.py:188} INFO - [2025-02-21T08:19:01.939+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:19:02.907+0000] {logging_mixin.py:188} INFO - [2025-02-21T08:19:02.888+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/optum_ml_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/optum_ml_dag.py", line 7, in <module>
    from sklearn.ensemble import RandomForestClassifier
ModuleNotFoundError: No module named 'sklearn'
[2025-02-21T08:19:02.915+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:19:02.966+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/optum_ml_dag.py took 1.073 seconds
[2025-02-21T08:19:33.385+0000] {processor.py:161} INFO - Started process (PID=14139) to work on /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:19:33.389+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/optum_ml_dag.py for tasks to queue
[2025-02-21T08:19:33.392+0000] {logging_mixin.py:188} INFO - [2025-02-21T08:19:33.391+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:19:34.287+0000] {logging_mixin.py:188} INFO - [2025-02-21T08:19:34.261+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/optum_ml_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/optum_ml_dag.py", line 7, in <module>
    from sklearn.ensemble import RandomForestClassifier
ModuleNotFoundError: No module named 'sklearn'
[2025-02-21T08:19:34.295+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:19:34.373+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/optum_ml_dag.py took 1.005 seconds
[2025-02-21T08:20:04.719+0000] {processor.py:161} INFO - Started process (PID=14203) to work on /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:20:04.722+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/optum_ml_dag.py for tasks to queue
[2025-02-21T08:20:04.727+0000] {logging_mixin.py:188} INFO - [2025-02-21T08:20:04.726+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:20:05.656+0000] {logging_mixin.py:188} INFO - [2025-02-21T08:20:05.632+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/optum_ml_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/optum_ml_dag.py", line 7, in <module>
    from sklearn.ensemble import RandomForestClassifier
ModuleNotFoundError: No module named 'sklearn'
[2025-02-21T08:20:05.662+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:20:05.720+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/optum_ml_dag.py took 1.011 seconds
[2025-02-21T08:20:36.341+0000] {processor.py:161} INFO - Started process (PID=14267) to work on /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:20:36.344+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/optum_ml_dag.py for tasks to queue
[2025-02-21T08:20:36.349+0000] {logging_mixin.py:188} INFO - [2025-02-21T08:20:36.348+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:20:37.182+0000] {logging_mixin.py:188} INFO - [2025-02-21T08:20:37.164+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/optum_ml_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/optum_ml_dag.py", line 7, in <module>
    from sklearn.ensemble import RandomForestClassifier
ModuleNotFoundError: No module named 'sklearn'
[2025-02-21T08:20:37.189+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:20:37.257+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/optum_ml_dag.py took 0.928 seconds
[2025-02-21T08:21:07.711+0000] {processor.py:161} INFO - Started process (PID=14332) to work on /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:21:07.715+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/optum_ml_dag.py for tasks to queue
[2025-02-21T08:21:07.718+0000] {logging_mixin.py:188} INFO - [2025-02-21T08:21:07.718+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:21:08.722+0000] {logging_mixin.py:188} INFO - [2025-02-21T08:21:08.694+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/optum_ml_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/optum_ml_dag.py", line 7, in <module>
    from sklearn.ensemble import RandomForestClassifier
ModuleNotFoundError: No module named 'sklearn'
[2025-02-21T08:21:08.730+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:21:08.777+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/optum_ml_dag.py took 1.079 seconds
[2025-02-21T08:21:39.267+0000] {processor.py:161} INFO - Started process (PID=14395) to work on /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:21:39.271+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/optum_ml_dag.py for tasks to queue
[2025-02-21T08:21:39.276+0000] {logging_mixin.py:188} INFO - [2025-02-21T08:21:39.275+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:21:40.437+0000] {logging_mixin.py:188} INFO - [2025-02-21T08:21:40.419+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/optum_ml_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/optum_ml_dag.py", line 7, in <module>
    from sklearn.ensemble import RandomForestClassifier
ModuleNotFoundError: No module named 'sklearn'
[2025-02-21T08:21:40.442+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:21:40.499+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/optum_ml_dag.py took 1.247 seconds
[2025-02-21T08:22:10.965+0000] {processor.py:161} INFO - Started process (PID=14460) to work on /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:22:10.969+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/optum_ml_dag.py for tasks to queue
[2025-02-21T08:22:10.973+0000] {logging_mixin.py:188} INFO - [2025-02-21T08:22:10.972+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:22:11.872+0000] {logging_mixin.py:188} INFO - [2025-02-21T08:22:11.856+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/optum_ml_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/optum_ml_dag.py", line 7, in <module>
    from sklearn.ensemble import RandomForestClassifier
ModuleNotFoundError: No module named 'sklearn'
[2025-02-21T08:22:11.877+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:22:11.934+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/optum_ml_dag.py took 0.977 seconds
[2025-02-21T08:22:42.108+0000] {processor.py:161} INFO - Started process (PID=14524) to work on /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:22:42.112+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/optum_ml_dag.py for tasks to queue
[2025-02-21T08:22:42.115+0000] {logging_mixin.py:188} INFO - [2025-02-21T08:22:42.114+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:22:43.409+0000] {logging_mixin.py:188} INFO - [2025-02-21T08:22:43.385+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/optum_ml_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/optum_ml_dag.py", line 7, in <module>
    from sklearn.ensemble import RandomForestClassifier
ModuleNotFoundError: No module named 'sklearn'
[2025-02-21T08:22:43.414+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:22:43.476+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/optum_ml_dag.py took 1.377 seconds
[2025-02-21T08:23:14.225+0000] {processor.py:161} INFO - Started process (PID=14590) to work on /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:23:14.232+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/optum_ml_dag.py for tasks to queue
[2025-02-21T08:23:14.238+0000] {logging_mixin.py:188} INFO - [2025-02-21T08:23:14.238+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:23:15.829+0000] {logging_mixin.py:188} INFO - [2025-02-21T08:23:15.812+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/optum_ml_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/optum_ml_dag.py", line 7, in <module>
    from sklearn.ensemble import RandomForestClassifier
ModuleNotFoundError: No module named 'sklearn'
[2025-02-21T08:23:15.832+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:23:15.869+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/optum_ml_dag.py took 1.655 seconds
[2025-02-21T08:23:46.404+0000] {processor.py:161} INFO - Started process (PID=14655) to work on /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:23:46.408+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/optum_ml_dag.py for tasks to queue
[2025-02-21T08:23:46.411+0000] {logging_mixin.py:188} INFO - [2025-02-21T08:23:46.410+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:23:47.674+0000] {logging_mixin.py:188} INFO - [2025-02-21T08:23:47.655+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/optum_ml_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/optum_ml_dag.py", line 7, in <module>
    from sklearn.ensemble import RandomForestClassifier
ModuleNotFoundError: No module named 'sklearn'
[2025-02-21T08:23:47.681+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:23:47.737+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/optum_ml_dag.py took 1.342 seconds
[2025-02-21T08:24:18.426+0000] {processor.py:161} INFO - Started process (PID=14721) to work on /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:24:18.430+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/optum_ml_dag.py for tasks to queue
[2025-02-21T08:24:18.434+0000] {logging_mixin.py:188} INFO - [2025-02-21T08:24:18.433+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:24:20.123+0000] {logging_mixin.py:188} INFO - [2025-02-21T08:24:20.082+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/optum_ml_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/optum_ml_dag.py", line 7, in <module>
    from sklearn.ensemble import RandomForestClassifier
ModuleNotFoundError: No module named 'sklearn'
[2025-02-21T08:24:20.132+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:24:20.203+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/optum_ml_dag.py took 1.786 seconds
[2025-02-21T08:24:50.453+0000] {processor.py:161} INFO - Started process (PID=14787) to work on /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:24:50.458+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/optum_ml_dag.py for tasks to queue
[2025-02-21T08:24:50.461+0000] {logging_mixin.py:188} INFO - [2025-02-21T08:24:50.460+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:24:51.896+0000] {logging_mixin.py:188} INFO - [2025-02-21T08:24:51.883+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/optum_ml_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/optum_ml_dag.py", line 7, in <module>
    from sklearn.ensemble import RandomForestClassifier
ModuleNotFoundError: No module named 'sklearn'
[2025-02-21T08:24:51.900+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:24:51.949+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/optum_ml_dag.py took 1.507 seconds
[2025-02-21T08:25:22.347+0000] {processor.py:161} INFO - Started process (PID=14850) to work on /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:25:22.352+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/optum_ml_dag.py for tasks to queue
[2025-02-21T08:25:22.355+0000] {logging_mixin.py:188} INFO - [2025-02-21T08:25:22.355+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:25:23.599+0000] {logging_mixin.py:188} INFO - [2025-02-21T08:25:23.584+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/optum_ml_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/optum_ml_dag.py", line 7, in <module>
    from sklearn.ensemble import RandomForestClassifier
ModuleNotFoundError: No module named 'sklearn'
[2025-02-21T08:25:23.603+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:25:23.659+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/optum_ml_dag.py took 1.326 seconds
[2025-02-21T08:25:54.598+0000] {processor.py:161} INFO - Started process (PID=14916) to work on /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:25:54.602+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/optum_ml_dag.py for tasks to queue
[2025-02-21T08:25:54.605+0000] {logging_mixin.py:188} INFO - [2025-02-21T08:25:54.605+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:25:55.826+0000] {logging_mixin.py:188} INFO - [2025-02-21T08:25:55.808+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/optum_ml_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/optum_ml_dag.py", line 7, in <module>
    from sklearn.ensemble import RandomForestClassifier
ModuleNotFoundError: No module named 'sklearn'
[2025-02-21T08:25:55.831+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:25:55.884+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/optum_ml_dag.py took 1.299 seconds
[2025-02-21T08:26:26.649+0000] {processor.py:161} INFO - Started process (PID=14980) to work on /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:26:26.652+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/optum_ml_dag.py for tasks to queue
[2025-02-21T08:26:26.657+0000] {logging_mixin.py:188} INFO - [2025-02-21T08:26:26.657+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:26:27.931+0000] {logging_mixin.py:188} INFO - [2025-02-21T08:26:27.917+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/optum_ml_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/optum_ml_dag.py", line 7, in <module>
    from sklearn.ensemble import RandomForestClassifier
ModuleNotFoundError: No module named 'sklearn'
[2025-02-21T08:26:27.936+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:26:27.990+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/optum_ml_dag.py took 1.347 seconds
[2025-02-21T08:26:58.365+0000] {processor.py:161} INFO - Started process (PID=15046) to work on /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:26:58.368+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/optum_ml_dag.py for tasks to queue
[2025-02-21T08:26:58.373+0000] {logging_mixin.py:188} INFO - [2025-02-21T08:26:58.372+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:26:59.624+0000] {logging_mixin.py:188} INFO - [2025-02-21T08:26:59.595+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/optum_ml_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/optum_ml_dag.py", line 7, in <module>
    from sklearn.ensemble import RandomForestClassifier
ModuleNotFoundError: No module named 'sklearn'
[2025-02-21T08:26:59.638+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:26:59.698+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/optum_ml_dag.py took 1.345 seconds
[2025-02-21T08:27:30.345+0000] {processor.py:161} INFO - Started process (PID=15111) to work on /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:27:30.349+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/optum_ml_dag.py for tasks to queue
[2025-02-21T08:27:30.352+0000] {logging_mixin.py:188} INFO - [2025-02-21T08:27:30.352+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:27:31.582+0000] {logging_mixin.py:188} INFO - [2025-02-21T08:27:31.565+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/optum_ml_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/optum_ml_dag.py", line 7, in <module>
    from sklearn.ensemble import RandomForestClassifier
ModuleNotFoundError: No module named 'sklearn'
[2025-02-21T08:27:31.587+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:27:31.636+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/optum_ml_dag.py took 1.305 seconds
[2025-02-21T08:28:01.868+0000] {processor.py:161} INFO - Started process (PID=15175) to work on /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:28:01.881+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/optum_ml_dag.py for tasks to queue
[2025-02-21T08:28:01.887+0000] {logging_mixin.py:188} INFO - [2025-02-21T08:28:01.886+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:28:02.996+0000] {logging_mixin.py:188} INFO - [2025-02-21T08:28:02.973+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/optum_ml_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/optum_ml_dag.py", line 7, in <module>
    from sklearn.ensemble import RandomForestClassifier
ModuleNotFoundError: No module named 'sklearn'
[2025-02-21T08:28:03.003+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:28:03.075+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/optum_ml_dag.py took 1.227 seconds
[2025-02-21T08:28:33.704+0000] {processor.py:161} INFO - Started process (PID=15241) to work on /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:28:33.708+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/optum_ml_dag.py for tasks to queue
[2025-02-21T08:28:33.712+0000] {logging_mixin.py:188} INFO - [2025-02-21T08:28:33.711+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:28:35.077+0000] {logging_mixin.py:188} INFO - [2025-02-21T08:28:35.052+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/optum_ml_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/optum_ml_dag.py", line 7, in <module>
    from sklearn.ensemble import RandomForestClassifier
ModuleNotFoundError: No module named 'sklearn'
[2025-02-21T08:28:35.082+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:28:35.125+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/optum_ml_dag.py took 1.442 seconds
[2025-02-21T08:29:05.453+0000] {processor.py:161} INFO - Started process (PID=15311) to work on /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:29:05.459+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/optum_ml_dag.py for tasks to queue
[2025-02-21T08:29:05.461+0000] {logging_mixin.py:188} INFO - [2025-02-21T08:29:05.460+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:29:06.774+0000] {logging_mixin.py:188} INFO - [2025-02-21T08:29:06.760+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/optum_ml_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/optum_ml_dag.py", line 7, in <module>
    from sklearn.ensemble import RandomForestClassifier
ModuleNotFoundError: No module named 'sklearn'
[2025-02-21T08:29:06.780+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:29:06.827+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/optum_ml_dag.py took 1.381 seconds
[2025-02-21T08:29:37.124+0000] {processor.py:161} INFO - Started process (PID=15376) to work on /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:29:37.129+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/optum_ml_dag.py for tasks to queue
[2025-02-21T08:29:37.133+0000] {logging_mixin.py:188} INFO - [2025-02-21T08:29:37.132+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:29:38.595+0000] {logging_mixin.py:188} INFO - [2025-02-21T08:29:38.580+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/optum_ml_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/optum_ml_dag.py", line 7, in <module>
    from sklearn.ensemble import RandomForestClassifier
ModuleNotFoundError: No module named 'sklearn'
[2025-02-21T08:29:38.600+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:29:38.655+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/optum_ml_dag.py took 1.542 seconds
[2025-02-21T08:30:08.891+0000] {processor.py:161} INFO - Started process (PID=15441) to work on /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:30:08.896+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/optum_ml_dag.py for tasks to queue
[2025-02-21T08:30:08.900+0000] {logging_mixin.py:188} INFO - [2025-02-21T08:30:08.899+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:30:10.772+0000] {logging_mixin.py:188} INFO - [2025-02-21T08:30:10.748+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/optum_ml_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/optum_ml_dag.py", line 7, in <module>
    from sklearn.ensemble import RandomForestClassifier
ModuleNotFoundError: No module named 'sklearn'
[2025-02-21T08:30:10.780+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:30:10.839+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/optum_ml_dag.py took 1.969 seconds
[2025-02-21T08:30:41.422+0000] {processor.py:161} INFO - Started process (PID=15505) to work on /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:30:41.425+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/optum_ml_dag.py for tasks to queue
[2025-02-21T08:30:41.434+0000] {logging_mixin.py:188} INFO - [2025-02-21T08:30:41.433+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:30:42.877+0000] {logging_mixin.py:188} INFO - [2025-02-21T08:30:42.845+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/optum_ml_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/optum_ml_dag.py", line 7, in <module>
    from sklearn.ensemble import RandomForestClassifier
ModuleNotFoundError: No module named 'sklearn'
[2025-02-21T08:30:42.889+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:30:42.933+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/optum_ml_dag.py took 1.524 seconds
[2025-02-21T08:31:13.209+0000] {processor.py:161} INFO - Started process (PID=15570) to work on /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:31:13.212+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/optum_ml_dag.py for tasks to queue
[2025-02-21T08:31:13.215+0000] {logging_mixin.py:188} INFO - [2025-02-21T08:31:13.214+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:31:15.053+0000] {logging_mixin.py:188} INFO - [2025-02-21T08:31:15.034+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/optum_ml_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/optum_ml_dag.py", line 7, in <module>
    from sklearn.ensemble import RandomForestClassifier
ModuleNotFoundError: No module named 'sklearn'
[2025-02-21T08:31:15.061+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:31:15.129+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/optum_ml_dag.py took 1.926 seconds
[2025-02-21T08:31:45.702+0000] {processor.py:161} INFO - Started process (PID=15635) to work on /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:31:45.705+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/optum_ml_dag.py for tasks to queue
[2025-02-21T08:31:45.708+0000] {logging_mixin.py:188} INFO - [2025-02-21T08:31:45.707+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:31:46.879+0000] {logging_mixin.py:188} INFO - [2025-02-21T08:31:46.863+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/optum_ml_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/optum_ml_dag.py", line 7, in <module>
    from sklearn.ensemble import RandomForestClassifier
ModuleNotFoundError: No module named 'sklearn'
[2025-02-21T08:31:46.884+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:31:46.945+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/optum_ml_dag.py took 1.250 seconds
[2025-02-21T08:32:17.240+0000] {processor.py:161} INFO - Started process (PID=15700) to work on /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:32:17.244+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/optum_ml_dag.py for tasks to queue
[2025-02-21T08:32:17.248+0000] {logging_mixin.py:188} INFO - [2025-02-21T08:32:17.247+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:32:18.433+0000] {logging_mixin.py:188} INFO - [2025-02-21T08:32:18.418+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/optum_ml_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/optum_ml_dag.py", line 7, in <module>
    from sklearn.ensemble import RandomForestClassifier
ModuleNotFoundError: No module named 'sklearn'
[2025-02-21T08:32:18.438+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:32:18.496+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/optum_ml_dag.py took 1.270 seconds
[2025-02-21T08:32:49.493+0000] {processor.py:161} INFO - Started process (PID=15764) to work on /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:32:49.496+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/optum_ml_dag.py for tasks to queue
[2025-02-21T08:32:49.499+0000] {logging_mixin.py:188} INFO - [2025-02-21T08:32:49.498+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:32:50.855+0000] {logging_mixin.py:188} INFO - [2025-02-21T08:32:50.837+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/optum_ml_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/optum_ml_dag.py", line 7, in <module>
    from sklearn.ensemble import RandomForestClassifier
ModuleNotFoundError: No module named 'sklearn'
[2025-02-21T08:32:50.860+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:32:50.918+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/optum_ml_dag.py took 1.439 seconds
[2025-02-21T08:33:21.390+0000] {processor.py:161} INFO - Started process (PID=15828) to work on /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:33:21.400+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/optum_ml_dag.py for tasks to queue
[2025-02-21T08:33:21.408+0000] {logging_mixin.py:188} INFO - [2025-02-21T08:33:21.406+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:33:22.652+0000] {logging_mixin.py:188} INFO - [2025-02-21T08:33:22.635+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/optum_ml_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/optum_ml_dag.py", line 7, in <module>
    from sklearn.ensemble import RandomForestClassifier
ModuleNotFoundError: No module named 'sklearn'
[2025-02-21T08:33:22.659+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:33:22.714+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/optum_ml_dag.py took 1.347 seconds
[2025-02-21T08:33:53.736+0000] {processor.py:161} INFO - Started process (PID=15892) to work on /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:33:53.740+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/optum_ml_dag.py for tasks to queue
[2025-02-21T08:33:53.744+0000] {logging_mixin.py:188} INFO - [2025-02-21T08:33:53.743+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:33:55.165+0000] {logging_mixin.py:188} INFO - [2025-02-21T08:33:55.149+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/optum_ml_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/optum_ml_dag.py", line 7, in <module>
    from sklearn.ensemble import RandomForestClassifier
ModuleNotFoundError: No module named 'sklearn'
[2025-02-21T08:33:55.170+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:33:55.227+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/optum_ml_dag.py took 1.509 seconds
[2025-02-21T08:34:25.636+0000] {processor.py:161} INFO - Started process (PID=15957) to work on /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:34:25.639+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/optum_ml_dag.py for tasks to queue
[2025-02-21T08:34:25.643+0000] {logging_mixin.py:188} INFO - [2025-02-21T08:34:25.642+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:34:26.949+0000] {logging_mixin.py:188} INFO - [2025-02-21T08:34:26.936+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/optum_ml_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/optum_ml_dag.py", line 7, in <module>
    from sklearn.ensemble import RandomForestClassifier
ModuleNotFoundError: No module named 'sklearn'
[2025-02-21T08:34:26.954+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:34:27.003+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/optum_ml_dag.py took 1.379 seconds
[2025-02-21T08:34:57.964+0000] {processor.py:161} INFO - Started process (PID=16022) to work on /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:34:57.968+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/optum_ml_dag.py for tasks to queue
[2025-02-21T08:34:57.972+0000] {logging_mixin.py:188} INFO - [2025-02-21T08:34:57.971+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:34:59.188+0000] {logging_mixin.py:188} INFO - [2025-02-21T08:34:59.175+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/optum_ml_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/optum_ml_dag.py", line 7, in <module>
    from sklearn.ensemble import RandomForestClassifier
ModuleNotFoundError: No module named 'sklearn'
[2025-02-21T08:34:59.197+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:34:59.257+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/optum_ml_dag.py took 1.310 seconds
[2025-02-21T08:35:30.319+0000] {processor.py:161} INFO - Started process (PID=16087) to work on /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:35:30.324+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/optum_ml_dag.py for tasks to queue
[2025-02-21T08:35:30.327+0000] {logging_mixin.py:188} INFO - [2025-02-21T08:35:30.326+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:35:31.605+0000] {logging_mixin.py:188} INFO - [2025-02-21T08:35:31.586+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/optum_ml_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/optum_ml_dag.py", line 7, in <module>
    from sklearn.ensemble import RandomForestClassifier
ModuleNotFoundError: No module named 'sklearn'
[2025-02-21T08:35:31.612+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:35:31.672+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/optum_ml_dag.py took 1.362 seconds
[2025-02-21T08:36:02.464+0000] {processor.py:161} INFO - Started process (PID=16153) to work on /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:36:02.468+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/optum_ml_dag.py for tasks to queue
[2025-02-21T08:36:02.472+0000] {logging_mixin.py:188} INFO - [2025-02-21T08:36:02.471+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:36:04.020+0000] {logging_mixin.py:188} INFO - [2025-02-21T08:36:04.001+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/optum_ml_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/optum_ml_dag.py", line 7, in <module>
    from sklearn.ensemble import RandomForestClassifier
ModuleNotFoundError: No module named 'sklearn'
[2025-02-21T08:36:04.027+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:36:04.097+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/optum_ml_dag.py took 1.649 seconds
[2025-02-21T08:36:34.571+0000] {processor.py:161} INFO - Started process (PID=16216) to work on /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:36:34.575+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/optum_ml_dag.py for tasks to queue
[2025-02-21T08:36:34.578+0000] {logging_mixin.py:188} INFO - [2025-02-21T08:36:34.577+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:36:35.775+0000] {logging_mixin.py:188} INFO - [2025-02-21T08:36:35.764+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/optum_ml_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/optum_ml_dag.py", line 7, in <module>
    from sklearn.ensemble import RandomForestClassifier
ModuleNotFoundError: No module named 'sklearn'
[2025-02-21T08:36:35.783+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:36:35.838+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/optum_ml_dag.py took 1.280 seconds
[2025-02-21T08:37:06.190+0000] {processor.py:161} INFO - Started process (PID=16279) to work on /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:37:06.194+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/optum_ml_dag.py for tasks to queue
[2025-02-21T08:37:06.197+0000] {logging_mixin.py:188} INFO - [2025-02-21T08:37:06.196+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:37:07.307+0000] {logging_mixin.py:188} INFO - [2025-02-21T08:37:07.287+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/optum_ml_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/optum_ml_dag.py", line 7, in <module>
    from sklearn.ensemble import RandomForestClassifier
ModuleNotFoundError: No module named 'sklearn'
[2025-02-21T08:37:07.313+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:37:07.369+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/optum_ml_dag.py took 1.190 seconds
[2025-02-21T08:37:37.973+0000] {processor.py:161} INFO - Started process (PID=16345) to work on /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:37:37.976+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/optum_ml_dag.py for tasks to queue
[2025-02-21T08:37:37.984+0000] {logging_mixin.py:188} INFO - [2025-02-21T08:37:37.981+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:37:39.496+0000] {logging_mixin.py:188} INFO - [2025-02-21T08:37:39.475+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/optum_ml_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/optum_ml_dag.py", line 7, in <module>
    from sklearn.ensemble import RandomForestClassifier
ModuleNotFoundError: No module named 'sklearn'
[2025-02-21T08:37:39.502+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:37:39.566+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/optum_ml_dag.py took 1.601 seconds
[2025-02-21T08:38:10.176+0000] {processor.py:161} INFO - Started process (PID=16416) to work on /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:38:10.179+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/optum_ml_dag.py for tasks to queue
[2025-02-21T08:38:10.183+0000] {logging_mixin.py:188} INFO - [2025-02-21T08:38:10.182+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:38:11.630+0000] {logging_mixin.py:188} INFO - [2025-02-21T08:38:11.610+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/optum_ml_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/optum_ml_dag.py", line 7, in <module>
    from sklearn.ensemble import RandomForestClassifier
ModuleNotFoundError: No module named 'sklearn'
[2025-02-21T08:38:11.643+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:38:11.738+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/optum_ml_dag.py took 1.573 seconds
[2025-02-21T08:38:42.283+0000] {processor.py:161} INFO - Started process (PID=16483) to work on /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:38:42.288+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/optum_ml_dag.py for tasks to queue
[2025-02-21T08:38:42.293+0000] {logging_mixin.py:188} INFO - [2025-02-21T08:38:42.292+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:38:43.527+0000] {logging_mixin.py:188} INFO - [2025-02-21T08:38:43.511+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/optum_ml_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/optum_ml_dag.py", line 7, in <module>
    from sklearn.ensemble import RandomForestClassifier
ModuleNotFoundError: No module named 'sklearn'
[2025-02-21T08:38:43.533+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:38:43.587+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/optum_ml_dag.py took 1.319 seconds
[2025-02-21T08:39:14.293+0000] {processor.py:161} INFO - Started process (PID=16547) to work on /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:39:14.301+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/optum_ml_dag.py for tasks to queue
[2025-02-21T08:39:14.306+0000] {logging_mixin.py:188} INFO - [2025-02-21T08:39:14.304+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:39:15.866+0000] {logging_mixin.py:188} INFO - [2025-02-21T08:39:15.843+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/optum_ml_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/optum_ml_dag.py", line 7, in <module>
    from sklearn.ensemble import RandomForestClassifier
ModuleNotFoundError: No module named 'sklearn'
[2025-02-21T08:39:15.871+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:39:15.960+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/optum_ml_dag.py took 1.677 seconds
[2025-02-21T08:39:46.526+0000] {processor.py:161} INFO - Started process (PID=16611) to work on /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:39:46.529+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/optum_ml_dag.py for tasks to queue
[2025-02-21T08:39:46.532+0000] {logging_mixin.py:188} INFO - [2025-02-21T08:39:46.531+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:39:47.962+0000] {logging_mixin.py:188} INFO - [2025-02-21T08:39:47.937+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/optum_ml_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/optum_ml_dag.py", line 7, in <module>
    from sklearn.ensemble import RandomForestClassifier
ModuleNotFoundError: No module named 'sklearn'
[2025-02-21T08:39:47.968+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:39:48.038+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/optum_ml_dag.py took 1.521 seconds
[2025-02-21T08:40:18.313+0000] {processor.py:161} INFO - Started process (PID=16675) to work on /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:40:18.318+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/optum_ml_dag.py for tasks to queue
[2025-02-21T08:40:18.322+0000] {logging_mixin.py:188} INFO - [2025-02-21T08:40:18.321+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:40:19.631+0000] {logging_mixin.py:188} INFO - [2025-02-21T08:40:19.618+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/optum_ml_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/optum_ml_dag.py", line 7, in <module>
    from sklearn.ensemble import RandomForestClassifier
ModuleNotFoundError: No module named 'sklearn'
[2025-02-21T08:40:19.635+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:40:19.676+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/optum_ml_dag.py took 1.378 seconds
[2025-02-21T08:40:50.100+0000] {processor.py:161} INFO - Started process (PID=16741) to work on /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:40:50.104+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/optum_ml_dag.py for tasks to queue
[2025-02-21T08:40:50.108+0000] {logging_mixin.py:188} INFO - [2025-02-21T08:40:50.107+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:40:51.205+0000] {logging_mixin.py:188} INFO - [2025-02-21T08:40:51.189+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/optum_ml_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/optum_ml_dag.py", line 7, in <module>
    from sklearn.ensemble import RandomForestClassifier
ModuleNotFoundError: No module named 'sklearn'
[2025-02-21T08:40:51.211+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:40:51.253+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/optum_ml_dag.py took 1.160 seconds
[2025-02-21T08:41:22.019+0000] {processor.py:161} INFO - Started process (PID=16807) to work on /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:41:22.028+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/optum_ml_dag.py for tasks to queue
[2025-02-21T08:41:22.032+0000] {logging_mixin.py:188} INFO - [2025-02-21T08:41:22.030+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:41:23.288+0000] {logging_mixin.py:188} INFO - [2025-02-21T08:41:23.273+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/optum_ml_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/optum_ml_dag.py", line 7, in <module>
    from sklearn.ensemble import RandomForestClassifier
ModuleNotFoundError: No module named 'sklearn'
[2025-02-21T08:41:23.293+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:41:23.345+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/optum_ml_dag.py took 1.335 seconds
[2025-02-21T08:41:53.884+0000] {processor.py:161} INFO - Started process (PID=16873) to work on /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:41:53.889+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/optum_ml_dag.py for tasks to queue
[2025-02-21T08:41:53.893+0000] {logging_mixin.py:188} INFO - [2025-02-21T08:41:53.892+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:41:55.113+0000] {logging_mixin.py:188} INFO - [2025-02-21T08:41:55.090+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/optum_ml_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/optum_ml_dag.py", line 7, in <module>
    from sklearn.ensemble import RandomForestClassifier
ModuleNotFoundError: No module named 'sklearn'
[2025-02-21T08:41:55.120+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:41:55.188+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/optum_ml_dag.py took 1.318 seconds
[2025-02-21T08:42:25.586+0000] {processor.py:161} INFO - Started process (PID=16939) to work on /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:42:25.590+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/optum_ml_dag.py for tasks to queue
[2025-02-21T08:42:25.596+0000] {logging_mixin.py:188} INFO - [2025-02-21T08:42:25.594+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:42:26.836+0000] {logging_mixin.py:188} INFO - [2025-02-21T08:42:26.818+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/optum_ml_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/optum_ml_dag.py", line 7, in <module>
    from sklearn.ensemble import RandomForestClassifier
ModuleNotFoundError: No module named 'sklearn'
[2025-02-21T08:42:26.842+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:42:26.889+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/optum_ml_dag.py took 1.318 seconds
[2025-02-21T08:42:57.485+0000] {processor.py:161} INFO - Started process (PID=17005) to work on /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:42:57.488+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/optum_ml_dag.py for tasks to queue
[2025-02-21T08:42:57.493+0000] {logging_mixin.py:188} INFO - [2025-02-21T08:42:57.492+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:42:58.716+0000] {logging_mixin.py:188} INFO - [2025-02-21T08:42:58.701+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/optum_ml_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/optum_ml_dag.py", line 7, in <module>
    from sklearn.ensemble import RandomForestClassifier
ModuleNotFoundError: No module named 'sklearn'
[2025-02-21T08:42:58.721+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:42:58.812+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/optum_ml_dag.py took 1.336 seconds
[2025-02-21T08:43:29.143+0000] {processor.py:161} INFO - Started process (PID=17070) to work on /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:43:29.147+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/optum_ml_dag.py for tasks to queue
[2025-02-21T08:43:29.150+0000] {logging_mixin.py:188} INFO - [2025-02-21T08:43:29.149+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:43:30.365+0000] {logging_mixin.py:188} INFO - [2025-02-21T08:43:30.349+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/optum_ml_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/optum_ml_dag.py", line 7, in <module>
    from sklearn.ensemble import RandomForestClassifier
ModuleNotFoundError: No module named 'sklearn'
[2025-02-21T08:43:30.370+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:43:30.419+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/optum_ml_dag.py took 1.290 seconds
[2025-02-21T08:44:00.656+0000] {processor.py:161} INFO - Started process (PID=17133) to work on /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:44:00.662+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/optum_ml_dag.py for tasks to queue
[2025-02-21T08:44:00.667+0000] {logging_mixin.py:188} INFO - [2025-02-21T08:44:00.666+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:44:02.363+0000] {logging_mixin.py:188} INFO - [2025-02-21T08:44:02.349+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/optum_ml_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/optum_ml_dag.py", line 7, in <module>
    from sklearn.ensemble import RandomForestClassifier
ModuleNotFoundError: No module named 'sklearn'
[2025-02-21T08:44:02.371+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:44:02.465+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/optum_ml_dag.py took 1.818 seconds
[2025-02-21T08:44:32.957+0000] {processor.py:161} INFO - Started process (PID=17199) to work on /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:44:32.965+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/optum_ml_dag.py for tasks to queue
[2025-02-21T08:44:32.969+0000] {logging_mixin.py:188} INFO - [2025-02-21T08:44:32.969+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:44:34.363+0000] {logging_mixin.py:188} INFO - [2025-02-21T08:44:34.342+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/optum_ml_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/optum_ml_dag.py", line 7, in <module>
    from sklearn.ensemble import RandomForestClassifier
ModuleNotFoundError: No module named 'sklearn'
[2025-02-21T08:44:34.371+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:44:34.426+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/optum_ml_dag.py took 1.510 seconds
[2025-02-21T08:45:04.732+0000] {processor.py:161} INFO - Started process (PID=17263) to work on /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:45:04.735+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/optum_ml_dag.py for tasks to queue
[2025-02-21T08:45:04.737+0000] {logging_mixin.py:188} INFO - [2025-02-21T08:45:04.737+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:45:05.933+0000] {logging_mixin.py:188} INFO - [2025-02-21T08:45:05.916+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/optum_ml_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/optum_ml_dag.py", line 7, in <module>
    from sklearn.ensemble import RandomForestClassifier
ModuleNotFoundError: No module named 'sklearn'
[2025-02-21T08:45:05.937+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:45:06.003+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/optum_ml_dag.py took 1.283 seconds
[2025-02-21T08:45:36.469+0000] {processor.py:161} INFO - Started process (PID=17327) to work on /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:45:36.473+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/optum_ml_dag.py for tasks to queue
[2025-02-21T08:45:36.477+0000] {logging_mixin.py:188} INFO - [2025-02-21T08:45:36.475+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:45:37.663+0000] {logging_mixin.py:188} INFO - [2025-02-21T08:45:37.638+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/optum_ml_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/optum_ml_dag.py", line 7, in <module>
    from sklearn.ensemble import RandomForestClassifier
ModuleNotFoundError: No module named 'sklearn'
[2025-02-21T08:45:37.677+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:45:37.740+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/optum_ml_dag.py took 1.281 seconds
[2025-02-21T08:46:08.001+0000] {processor.py:161} INFO - Started process (PID=17391) to work on /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:46:08.005+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/optum_ml_dag.py for tasks to queue
[2025-02-21T08:46:08.008+0000] {logging_mixin.py:188} INFO - [2025-02-21T08:46:08.007+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:46:09.161+0000] {logging_mixin.py:188} INFO - [2025-02-21T08:46:09.116+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/optum_ml_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/optum_ml_dag.py", line 7, in <module>
    from sklearn.ensemble import RandomForestClassifier
ModuleNotFoundError: No module named 'sklearn'
[2025-02-21T08:46:09.166+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:46:09.214+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/optum_ml_dag.py took 1.226 seconds
[2025-02-21T08:46:39.635+0000] {processor.py:161} INFO - Started process (PID=17456) to work on /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:46:39.639+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/optum_ml_dag.py for tasks to queue
[2025-02-21T08:46:39.643+0000] {logging_mixin.py:188} INFO - [2025-02-21T08:46:39.642+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:46:40.882+0000] {logging_mixin.py:188} INFO - [2025-02-21T08:46:40.841+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/optum_ml_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/optum_ml_dag.py", line 7, in <module>
    from sklearn.ensemble import RandomForestClassifier
ModuleNotFoundError: No module named 'sklearn'
[2025-02-21T08:46:40.889+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:46:40.963+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/optum_ml_dag.py took 1.339 seconds
[2025-02-21T08:47:11.780+0000] {processor.py:161} INFO - Started process (PID=17521) to work on /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:47:11.785+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/optum_ml_dag.py for tasks to queue
[2025-02-21T08:47:11.788+0000] {logging_mixin.py:188} INFO - [2025-02-21T08:47:11.788+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:47:13.326+0000] {logging_mixin.py:188} INFO - [2025-02-21T08:47:13.305+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/optum_ml_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/optum_ml_dag.py", line 7, in <module>
    from sklearn.ensemble import RandomForestClassifier
ModuleNotFoundError: No module named 'sklearn'
[2025-02-21T08:47:13.335+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:47:13.405+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/optum_ml_dag.py took 1.641 seconds
[2025-02-21T08:47:43.645+0000] {processor.py:161} INFO - Started process (PID=17590) to work on /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:47:43.649+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/optum_ml_dag.py for tasks to queue
[2025-02-21T08:47:43.652+0000] {logging_mixin.py:188} INFO - [2025-02-21T08:47:43.651+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:47:44.372+0000] {logging_mixin.py:188} INFO - [2025-02-21T08:47:44.337+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/optum_ml_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/optum_ml_dag.py", line 7, in <module>
    from sklearn.ensemble import RandomForestClassifier
ModuleNotFoundError: No module named 'sklearn'
[2025-02-21T08:47:44.379+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:47:44.452+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/optum_ml_dag.py took 0.823 seconds
[2025-02-21T08:48:14.657+0000] {processor.py:161} INFO - Started process (PID=17654) to work on /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:48:14.661+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/optum_ml_dag.py for tasks to queue
[2025-02-21T08:48:14.663+0000] {logging_mixin.py:188} INFO - [2025-02-21T08:48:14.663+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:48:15.698+0000] {logging_mixin.py:188} INFO - [2025-02-21T08:48:15.676+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/optum_ml_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/optum_ml_dag.py", line 7, in <module>
    from sklearn.ensemble import RandomForestClassifier
ModuleNotFoundError: No module named 'sklearn'
[2025-02-21T08:48:15.705+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:48:15.780+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/optum_ml_dag.py took 1.132 seconds
[2025-02-21T08:48:46.494+0000] {processor.py:161} INFO - Started process (PID=17717) to work on /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:48:46.498+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/optum_ml_dag.py for tasks to queue
[2025-02-21T08:48:46.501+0000] {logging_mixin.py:188} INFO - [2025-02-21T08:48:46.500+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:48:47.380+0000] {logging_mixin.py:188} INFO - [2025-02-21T08:48:47.366+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/optum_ml_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/optum_ml_dag.py", line 7, in <module>
    from sklearn.ensemble import RandomForestClassifier
ModuleNotFoundError: No module named 'sklearn'
[2025-02-21T08:48:47.384+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:48:47.435+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/optum_ml_dag.py took 0.965 seconds
[2025-02-21T08:49:17.732+0000] {processor.py:161} INFO - Started process (PID=17780) to work on /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:49:17.739+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/optum_ml_dag.py for tasks to queue
[2025-02-21T08:49:17.745+0000] {logging_mixin.py:188} INFO - [2025-02-21T08:49:17.744+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:49:18.811+0000] {logging_mixin.py:188} INFO - [2025-02-21T08:49:18.774+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/optum_ml_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/optum_ml_dag.py", line 7, in <module>
    from sklearn.ensemble import RandomForestClassifier
ModuleNotFoundError: No module named 'sklearn'
[2025-02-21T08:49:18.816+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:49:18.877+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/optum_ml_dag.py took 1.164 seconds
[2025-02-21T08:49:49.464+0000] {processor.py:161} INFO - Started process (PID=17845) to work on /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:49:49.468+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/optum_ml_dag.py for tasks to queue
[2025-02-21T08:49:49.472+0000] {logging_mixin.py:188} INFO - [2025-02-21T08:49:49.470+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:49:50.438+0000] {logging_mixin.py:188} INFO - [2025-02-21T08:49:50.398+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/optum_ml_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/optum_ml_dag.py", line 7, in <module>
    from sklearn.ensemble import RandomForestClassifier
ModuleNotFoundError: No module named 'sklearn'
[2025-02-21T08:49:50.444+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:49:50.529+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/optum_ml_dag.py took 1.079 seconds
[2025-02-21T08:50:21.040+0000] {processor.py:161} INFO - Started process (PID=17908) to work on /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:50:21.043+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/optum_ml_dag.py for tasks to queue
[2025-02-21T08:50:21.047+0000] {logging_mixin.py:188} INFO - [2025-02-21T08:50:21.046+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:50:21.958+0000] {logging_mixin.py:188} INFO - [2025-02-21T08:50:21.941+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/optum_ml_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/optum_ml_dag.py", line 7, in <module>
    from sklearn.ensemble import RandomForestClassifier
ModuleNotFoundError: No module named 'sklearn'
[2025-02-21T08:50:21.964+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:50:22.010+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/optum_ml_dag.py took 0.978 seconds
[2025-02-21T08:50:52.499+0000] {processor.py:161} INFO - Started process (PID=17973) to work on /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:50:52.504+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/optum_ml_dag.py for tasks to queue
[2025-02-21T08:50:52.509+0000] {logging_mixin.py:188} INFO - [2025-02-21T08:50:52.508+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:50:53.398+0000] {logging_mixin.py:188} INFO - [2025-02-21T08:50:53.381+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/optum_ml_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/optum_ml_dag.py", line 7, in <module>
    from sklearn.ensemble import RandomForestClassifier
ModuleNotFoundError: No module named 'sklearn'
[2025-02-21T08:50:53.403+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:50:53.464+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/optum_ml_dag.py took 0.980 seconds
[2025-02-21T08:51:24.060+0000] {processor.py:161} INFO - Started process (PID=18037) to work on /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:51:24.064+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/optum_ml_dag.py for tasks to queue
[2025-02-21T08:51:24.068+0000] {logging_mixin.py:188} INFO - [2025-02-21T08:51:24.067+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:51:24.923+0000] {logging_mixin.py:188} INFO - [2025-02-21T08:51:24.905+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/optum_ml_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/optum_ml_dag.py", line 7, in <module>
    from sklearn.ensemble import RandomForestClassifier
ModuleNotFoundError: No module named 'sklearn'
[2025-02-21T08:51:24.929+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:51:24.987+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/optum_ml_dag.py took 0.938 seconds
[2025-02-21T08:51:55.261+0000] {processor.py:161} INFO - Started process (PID=18103) to work on /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:51:55.265+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/optum_ml_dag.py for tasks to queue
[2025-02-21T08:51:55.267+0000] {logging_mixin.py:188} INFO - [2025-02-21T08:51:55.267+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:51:56.390+0000] {logging_mixin.py:188} INFO - [2025-02-21T08:51:56.346+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/optum_ml_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/optum_ml_dag.py", line 7, in <module>
    from sklearn.ensemble import RandomForestClassifier
ModuleNotFoundError: No module named 'sklearn'
[2025-02-21T08:51:56.412+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:51:56.521+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/optum_ml_dag.py took 1.268 seconds
[2025-02-21T08:52:27.156+0000] {processor.py:161} INFO - Started process (PID=18167) to work on /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:52:27.161+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/optum_ml_dag.py for tasks to queue
[2025-02-21T08:52:27.164+0000] {logging_mixin.py:188} INFO - [2025-02-21T08:52:27.163+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:52:28.019+0000] {logging_mixin.py:188} INFO - [2025-02-21T08:52:27.981+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/optum_ml_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/optum_ml_dag.py", line 7, in <module>
    from sklearn.ensemble import RandomForestClassifier
ModuleNotFoundError: No module named 'sklearn'
[2025-02-21T08:52:28.027+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:52:28.088+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/optum_ml_dag.py took 0.944 seconds
[2025-02-21T08:52:58.421+0000] {processor.py:161} INFO - Started process (PID=18231) to work on /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:52:58.428+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/optum_ml_dag.py for tasks to queue
[2025-02-21T08:52:58.434+0000] {logging_mixin.py:188} INFO - [2025-02-21T08:52:58.432+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:52:59.511+0000] {logging_mixin.py:188} INFO - [2025-02-21T08:52:59.445+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/optum_ml_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/optum_ml_dag.py", line 7, in <module>
    from sklearn.ensemble import RandomForestClassifier
ModuleNotFoundError: No module named 'sklearn'
[2025-02-21T08:52:59.529+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:52:59.630+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/optum_ml_dag.py took 1.223 seconds
[2025-02-21T08:53:29.846+0000] {processor.py:161} INFO - Started process (PID=18294) to work on /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:53:29.849+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/optum_ml_dag.py for tasks to queue
[2025-02-21T08:53:29.851+0000] {logging_mixin.py:188} INFO - [2025-02-21T08:53:29.851+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:53:30.576+0000] {logging_mixin.py:188} INFO - [2025-02-21T08:53:30.556+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/optum_ml_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/optum_ml_dag.py", line 7, in <module>
    from sklearn.ensemble import RandomForestClassifier
ModuleNotFoundError: No module named 'sklearn'
[2025-02-21T08:53:30.583+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:53:30.642+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/optum_ml_dag.py took 0.805 seconds
[2025-02-21T08:54:00.846+0000] {processor.py:161} INFO - Started process (PID=18357) to work on /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:54:00.853+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/optum_ml_dag.py for tasks to queue
[2025-02-21T08:54:00.858+0000] {logging_mixin.py:188} INFO - [2025-02-21T08:54:00.857+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:54:01.866+0000] {logging_mixin.py:188} INFO - [2025-02-21T08:54:01.840+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/optum_ml_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/optum_ml_dag.py", line 7, in <module>
    from sklearn.ensemble import RandomForestClassifier
ModuleNotFoundError: No module named 'sklearn'
[2025-02-21T08:54:01.873+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:54:01.932+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/optum_ml_dag.py took 1.095 seconds
[2025-02-21T08:54:32.303+0000] {processor.py:161} INFO - Started process (PID=18420) to work on /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:54:32.307+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/optum_ml_dag.py for tasks to queue
[2025-02-21T08:54:32.309+0000] {logging_mixin.py:188} INFO - [2025-02-21T08:54:32.309+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:54:33.251+0000] {logging_mixin.py:188} INFO - [2025-02-21T08:54:33.216+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/optum_ml_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/optum_ml_dag.py", line 7, in <module>
    from sklearn.ensemble import RandomForestClassifier
ModuleNotFoundError: No module named 'sklearn'
[2025-02-21T08:54:33.257+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:54:33.328+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/optum_ml_dag.py took 1.050 seconds
[2025-02-21T08:55:03.757+0000] {processor.py:161} INFO - Started process (PID=18485) to work on /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:55:03.761+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/optum_ml_dag.py for tasks to queue
[2025-02-21T08:55:03.763+0000] {logging_mixin.py:188} INFO - [2025-02-21T08:55:03.763+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:55:04.660+0000] {logging_mixin.py:188} INFO - [2025-02-21T08:55:04.642+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/optum_ml_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/optum_ml_dag.py", line 7, in <module>
    from sklearn.ensemble import RandomForestClassifier
ModuleNotFoundError: No module named 'sklearn'
[2025-02-21T08:55:04.664+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:55:04.708+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/optum_ml_dag.py took 0.974 seconds
[2025-02-21T08:55:34.982+0000] {processor.py:161} INFO - Started process (PID=18550) to work on /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:55:34.985+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/optum_ml_dag.py for tasks to queue
[2025-02-21T08:55:34.988+0000] {logging_mixin.py:188} INFO - [2025-02-21T08:55:34.987+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:55:35.906+0000] {logging_mixin.py:188} INFO - [2025-02-21T08:55:35.872+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/optum_ml_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/optum_ml_dag.py", line 7, in <module>
    from sklearn.ensemble import RandomForestClassifier
ModuleNotFoundError: No module named 'sklearn'
[2025-02-21T08:55:35.917+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:55:35.989+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/optum_ml_dag.py took 1.013 seconds
[2025-02-21T08:56:06.437+0000] {processor.py:161} INFO - Started process (PID=18613) to work on /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:56:06.442+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/optum_ml_dag.py for tasks to queue
[2025-02-21T08:56:06.446+0000] {logging_mixin.py:188} INFO - [2025-02-21T08:56:06.445+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:56:07.177+0000] {logging_mixin.py:188} INFO - [2025-02-21T08:56:07.164+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/optum_ml_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/optum_ml_dag.py", line 7, in <module>
    from sklearn.ensemble import RandomForestClassifier
ModuleNotFoundError: No module named 'sklearn'
[2025-02-21T08:56:07.181+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:56:07.223+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/optum_ml_dag.py took 0.822 seconds
[2025-02-21T08:56:37.768+0000] {processor.py:161} INFO - Started process (PID=18676) to work on /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:56:37.772+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/optum_ml_dag.py for tasks to queue
[2025-02-21T08:56:37.775+0000] {logging_mixin.py:188} INFO - [2025-02-21T08:56:37.774+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:56:38.792+0000] {logging_mixin.py:188} INFO - [2025-02-21T08:56:38.766+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/optum_ml_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/optum_ml_dag.py", line 7, in <module>
    from sklearn.ensemble import RandomForestClassifier
ModuleNotFoundError: No module named 'sklearn'
[2025-02-21T08:56:38.799+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:56:38.846+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/optum_ml_dag.py took 1.093 seconds
[2025-02-21T08:57:09.088+0000] {processor.py:161} INFO - Started process (PID=18741) to work on /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:57:09.092+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/optum_ml_dag.py for tasks to queue
[2025-02-21T08:57:09.097+0000] {logging_mixin.py:188} INFO - [2025-02-21T08:57:09.095+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:57:10.328+0000] {logging_mixin.py:188} INFO - [2025-02-21T08:57:10.294+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/optum_ml_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/optum_ml_dag.py", line 7, in <module>
    from sklearn.ensemble import RandomForestClassifier
ModuleNotFoundError: No module named 'sklearn'
[2025-02-21T08:57:10.336+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:57:10.394+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/optum_ml_dag.py took 1.318 seconds
[2025-02-21T08:57:40.886+0000] {processor.py:161} INFO - Started process (PID=18804) to work on /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:57:40.890+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/optum_ml_dag.py for tasks to queue
[2025-02-21T08:57:40.894+0000] {logging_mixin.py:188} INFO - [2025-02-21T08:57:40.893+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:57:41.921+0000] {logging_mixin.py:188} INFO - [2025-02-21T08:57:41.896+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/optum_ml_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/optum_ml_dag.py", line 7, in <module>
    from sklearn.ensemble import RandomForestClassifier
ModuleNotFoundError: No module named 'sklearn'
[2025-02-21T08:57:41.931+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:57:42.011+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/optum_ml_dag.py took 1.131 seconds
[2025-02-21T08:58:12.376+0000] {processor.py:161} INFO - Started process (PID=18868) to work on /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:58:12.380+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/optum_ml_dag.py for tasks to queue
[2025-02-21T08:58:12.384+0000] {logging_mixin.py:188} INFO - [2025-02-21T08:58:12.383+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:58:13.327+0000] {logging_mixin.py:188} INFO - [2025-02-21T08:58:13.314+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/optum_ml_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/optum_ml_dag.py", line 7, in <module>
    from sklearn.ensemble import RandomForestClassifier
ModuleNotFoundError: No module named 'sklearn'
[2025-02-21T08:58:13.331+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:58:13.396+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/optum_ml_dag.py took 1.028 seconds
[2025-02-21T08:58:43.674+0000] {processor.py:161} INFO - Started process (PID=18932) to work on /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:58:43.678+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/optum_ml_dag.py for tasks to queue
[2025-02-21T08:58:43.682+0000] {logging_mixin.py:188} INFO - [2025-02-21T08:58:43.681+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:58:44.815+0000] {logging_mixin.py:188} INFO - [2025-02-21T08:58:44.797+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/optum_ml_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/optum_ml_dag.py", line 7, in <module>
    from sklearn.ensemble import RandomForestClassifier
ModuleNotFoundError: No module named 'sklearn'
[2025-02-21T08:58:44.820+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:58:44.867+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/optum_ml_dag.py took 1.207 seconds
[2025-02-21T08:59:15.375+0000] {processor.py:161} INFO - Started process (PID=18997) to work on /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:59:15.378+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/optum_ml_dag.py for tasks to queue
[2025-02-21T08:59:15.381+0000] {logging_mixin.py:188} INFO - [2025-02-21T08:59:15.380+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:59:16.280+0000] {logging_mixin.py:188} INFO - [2025-02-21T08:59:16.254+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/optum_ml_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/optum_ml_dag.py", line 7, in <module>
    from sklearn.ensemble import RandomForestClassifier
ModuleNotFoundError: No module named 'sklearn'
[2025-02-21T08:59:16.296+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:59:16.373+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/optum_ml_dag.py took 1.015 seconds
[2025-02-21T08:59:46.957+0000] {processor.py:161} INFO - Started process (PID=19062) to work on /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:59:46.963+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/optum_ml_dag.py for tasks to queue
[2025-02-21T08:59:46.968+0000] {logging_mixin.py:188} INFO - [2025-02-21T08:59:46.967+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:59:47.789+0000] {logging_mixin.py:188} INFO - [2025-02-21T08:59:47.762+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/optum_ml_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/optum_ml_dag.py", line 7, in <module>
    from sklearn.ensemble import RandomForestClassifier
ModuleNotFoundError: No module named 'sklearn'
[2025-02-21T08:59:47.800+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T08:59:47.860+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/optum_ml_dag.py took 0.915 seconds
[2025-02-21T09:00:18.068+0000] {processor.py:161} INFO - Started process (PID=19125) to work on /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T09:00:18.072+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/optum_ml_dag.py for tasks to queue
[2025-02-21T09:00:18.075+0000] {logging_mixin.py:188} INFO - [2025-02-21T09:00:18.075+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T09:00:18.981+0000] {logging_mixin.py:188} INFO - [2025-02-21T09:00:18.957+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/optum_ml_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/optum_ml_dag.py", line 7, in <module>
    from sklearn.ensemble import RandomForestClassifier
ModuleNotFoundError: No module named 'sklearn'
[2025-02-21T09:00:18.994+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T09:00:19.116+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/optum_ml_dag.py took 1.061 seconds
[2025-02-21T09:00:49.798+0000] {processor.py:161} INFO - Started process (PID=19197) to work on /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T09:00:49.802+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/optum_ml_dag.py for tasks to queue
[2025-02-21T09:00:49.807+0000] {logging_mixin.py:188} INFO - [2025-02-21T09:00:49.806+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T09:00:50.689+0000] {logging_mixin.py:188} INFO - [2025-02-21T09:00:50.659+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/optum_ml_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/optum_ml_dag.py", line 7, in <module>
    from sklearn.ensemble import RandomForestClassifier
ModuleNotFoundError: No module named 'sklearn'
[2025-02-21T09:00:50.695+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T09:00:50.759+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/optum_ml_dag.py took 0.974 seconds
[2025-02-21T09:01:20.970+0000] {processor.py:161} INFO - Started process (PID=19261) to work on /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T09:01:20.973+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/optum_ml_dag.py for tasks to queue
[2025-02-21T09:01:20.975+0000] {logging_mixin.py:188} INFO - [2025-02-21T09:01:20.975+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T09:01:22.395+0000] {logging_mixin.py:188} INFO - [2025-02-21T09:01:22.339+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/optum_ml_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/optum_ml_dag.py", line 7, in <module>
    from sklearn.ensemble import RandomForestClassifier
ModuleNotFoundError: No module named 'sklearn'
[2025-02-21T09:01:22.414+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T09:01:22.530+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/optum_ml_dag.py took 1.565 seconds
[2025-02-21T09:01:53.063+0000] {processor.py:161} INFO - Started process (PID=19326) to work on /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T09:01:53.067+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/optum_ml_dag.py for tasks to queue
[2025-02-21T09:01:53.069+0000] {logging_mixin.py:188} INFO - [2025-02-21T09:01:53.069+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T09:01:54.107+0000] {logging_mixin.py:188} INFO - [2025-02-21T09:01:54.089+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/optum_ml_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/optum_ml_dag.py", line 7, in <module>
    from sklearn.ensemble import RandomForestClassifier
ModuleNotFoundError: No module named 'sklearn'
[2025-02-21T09:01:54.112+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T09:01:54.162+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/optum_ml_dag.py took 1.108 seconds
[2025-02-21T09:02:24.664+0000] {processor.py:161} INFO - Started process (PID=19388) to work on /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T09:02:24.669+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/optum_ml_dag.py for tasks to queue
[2025-02-21T09:02:24.673+0000] {logging_mixin.py:188} INFO - [2025-02-21T09:02:24.672+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T09:02:25.490+0000] {logging_mixin.py:188} INFO - [2025-02-21T09:02:25.469+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/optum_ml_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/optum_ml_dag.py", line 7, in <module>
    from sklearn.ensemble import RandomForestClassifier
ModuleNotFoundError: No module named 'sklearn'
[2025-02-21T09:02:25.495+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T09:02:25.540+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/optum_ml_dag.py took 0.887 seconds
[2025-02-21T09:02:56.146+0000] {processor.py:161} INFO - Started process (PID=19452) to work on /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T09:02:56.150+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/optum_ml_dag.py for tasks to queue
[2025-02-21T09:02:56.155+0000] {logging_mixin.py:188} INFO - [2025-02-21T09:02:56.154+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T09:02:57.025+0000] {logging_mixin.py:188} INFO - [2025-02-21T09:02:56.994+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/optum_ml_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/optum_ml_dag.py", line 7, in <module>
    from sklearn.ensemble import RandomForestClassifier
ModuleNotFoundError: No module named 'sklearn'
[2025-02-21T09:02:57.031+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T09:02:57.098+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/optum_ml_dag.py took 0.963 seconds
[2025-02-21T09:03:27.320+0000] {processor.py:161} INFO - Started process (PID=19516) to work on /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T09:03:27.325+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/optum_ml_dag.py for tasks to queue
[2025-02-21T09:03:27.329+0000] {logging_mixin.py:188} INFO - [2025-02-21T09:03:27.328+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T09:03:28.233+0000] {logging_mixin.py:188} INFO - [2025-02-21T09:03:28.218+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/optum_ml_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/optum_ml_dag.py", line 7, in <module>
    from sklearn.ensemble import RandomForestClassifier
ModuleNotFoundError: No module named 'sklearn'
[2025-02-21T09:03:28.237+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T09:03:28.288+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/optum_ml_dag.py took 0.979 seconds
[2025-02-21T09:03:58.700+0000] {processor.py:161} INFO - Started process (PID=19579) to work on /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T09:03:58.705+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/optum_ml_dag.py for tasks to queue
[2025-02-21T09:03:58.708+0000] {logging_mixin.py:188} INFO - [2025-02-21T09:03:58.707+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T09:03:59.585+0000] {logging_mixin.py:188} INFO - [2025-02-21T09:03:59.548+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/optum_ml_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/optum_ml_dag.py", line 7, in <module>
    from sklearn.ensemble import RandomForestClassifier
ModuleNotFoundError: No module named 'sklearn'
[2025-02-21T09:03:59.594+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T09:03:59.655+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/optum_ml_dag.py took 0.962 seconds
[2025-02-21T09:04:30.349+0000] {processor.py:161} INFO - Started process (PID=19642) to work on /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T09:04:30.354+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/optum_ml_dag.py for tasks to queue
[2025-02-21T09:04:30.357+0000] {logging_mixin.py:188} INFO - [2025-02-21T09:04:30.356+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T09:04:31.484+0000] {logging_mixin.py:188} INFO - [2025-02-21T09:04:31.459+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/optum_ml_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/optum_ml_dag.py", line 7, in <module>
    from sklearn.ensemble import RandomForestClassifier
ModuleNotFoundError: No module named 'sklearn'
[2025-02-21T09:04:31.491+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T09:04:31.591+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/optum_ml_dag.py took 1.253 seconds
[2025-02-21T09:05:02.377+0000] {processor.py:161} INFO - Started process (PID=19707) to work on /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T09:05:02.383+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/optum_ml_dag.py for tasks to queue
[2025-02-21T09:05:02.387+0000] {logging_mixin.py:188} INFO - [2025-02-21T09:05:02.387+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T09:05:03.513+0000] {logging_mixin.py:188} INFO - [2025-02-21T09:05:03.484+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/optum_ml_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/optum_ml_dag.py", line 7, in <module>
    from sklearn.ensemble import RandomForestClassifier
ModuleNotFoundError: No module named 'sklearn'
[2025-02-21T09:05:03.520+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T09:05:03.568+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/optum_ml_dag.py took 1.219 seconds
[2025-02-21T09:05:34.123+0000] {processor.py:161} INFO - Started process (PID=19771) to work on /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T09:05:34.130+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/optum_ml_dag.py for tasks to queue
[2025-02-21T09:05:34.136+0000] {logging_mixin.py:188} INFO - [2025-02-21T09:05:34.134+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T09:05:35.155+0000] {logging_mixin.py:188} INFO - [2025-02-21T09:05:35.126+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/optum_ml_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/optum_ml_dag.py", line 7, in <module>
    from sklearn.ensemble import RandomForestClassifier
ModuleNotFoundError: No module named 'sklearn'
[2025-02-21T09:05:35.165+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T09:05:35.267+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/optum_ml_dag.py took 1.172 seconds
[2025-02-21T09:06:05.609+0000] {processor.py:161} INFO - Started process (PID=19835) to work on /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T09:06:05.613+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/optum_ml_dag.py for tasks to queue
[2025-02-21T09:06:05.618+0000] {logging_mixin.py:188} INFO - [2025-02-21T09:06:05.617+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T09:06:06.690+0000] {logging_mixin.py:188} INFO - [2025-02-21T09:06:06.670+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/optum_ml_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/optum_ml_dag.py", line 7, in <module>
    from sklearn.ensemble import RandomForestClassifier
ModuleNotFoundError: No module named 'sklearn'
[2025-02-21T09:06:06.696+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T09:06:06.755+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/optum_ml_dag.py took 1.157 seconds
[2025-02-21T09:06:37.418+0000] {processor.py:161} INFO - Started process (PID=19898) to work on /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T09:06:37.421+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/optum_ml_dag.py for tasks to queue
[2025-02-21T09:06:37.424+0000] {logging_mixin.py:188} INFO - [2025-02-21T09:06:37.423+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T09:06:38.210+0000] {logging_mixin.py:188} INFO - [2025-02-21T09:06:38.193+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/optum_ml_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/optum_ml_dag.py", line 7, in <module>
    from sklearn.ensemble import RandomForestClassifier
ModuleNotFoundError: No module named 'sklearn'
[2025-02-21T09:06:38.215+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T09:06:38.270+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/optum_ml_dag.py took 0.859 seconds
[2025-02-21T09:07:08.613+0000] {processor.py:161} INFO - Started process (PID=19962) to work on /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T09:07:08.615+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/optum_ml_dag.py for tasks to queue
[2025-02-21T09:07:08.617+0000] {logging_mixin.py:188} INFO - [2025-02-21T09:07:08.617+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T09:07:09.777+0000] {logging_mixin.py:188} INFO - [2025-02-21T09:07:09.752+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/optum_ml_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/optum_ml_dag.py", line 7, in <module>
    from sklearn.ensemble import RandomForestClassifier
ModuleNotFoundError: No module named 'sklearn'
[2025-02-21T09:07:09.783+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T09:07:09.869+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/optum_ml_dag.py took 1.264 seconds
[2025-02-21T09:07:40.646+0000] {processor.py:161} INFO - Started process (PID=20028) to work on /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T09:07:40.649+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/optum_ml_dag.py for tasks to queue
[2025-02-21T09:07:40.652+0000] {logging_mixin.py:188} INFO - [2025-02-21T09:07:40.651+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T09:07:41.691+0000] {logging_mixin.py:188} INFO - [2025-02-21T09:07:41.675+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/optum_ml_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/optum_ml_dag.py", line 7, in <module>
    from sklearn.ensemble import RandomForestClassifier
ModuleNotFoundError: No module named 'sklearn'
[2025-02-21T09:07:41.696+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T09:07:41.752+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/optum_ml_dag.py took 1.117 seconds
[2025-02-21T09:08:12.179+0000] {processor.py:161} INFO - Started process (PID=20093) to work on /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T09:08:12.182+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/optum_ml_dag.py for tasks to queue
[2025-02-21T09:08:12.186+0000] {logging_mixin.py:188} INFO - [2025-02-21T09:08:12.185+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T09:08:13.238+0000] {logging_mixin.py:188} INFO - [2025-02-21T09:08:13.216+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/optum_ml_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/optum_ml_dag.py", line 7, in <module>
    from sklearn.ensemble import RandomForestClassifier
ModuleNotFoundError: No module named 'sklearn'
[2025-02-21T09:08:13.252+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T09:08:13.320+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/optum_ml_dag.py took 1.154 seconds
[2025-02-21T09:08:44.099+0000] {processor.py:161} INFO - Started process (PID=20157) to work on /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T09:08:44.105+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/optum_ml_dag.py for tasks to queue
[2025-02-21T09:08:44.108+0000] {logging_mixin.py:188} INFO - [2025-02-21T09:08:44.107+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T09:08:45.107+0000] {logging_mixin.py:188} INFO - [2025-02-21T09:08:45.084+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/optum_ml_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/optum_ml_dag.py", line 7, in <module>
    from sklearn.ensemble import RandomForestClassifier
ModuleNotFoundError: No module named 'sklearn'
[2025-02-21T09:08:45.118+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T09:08:45.177+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/optum_ml_dag.py took 1.090 seconds
[2025-02-21T09:09:15.807+0000] {processor.py:161} INFO - Started process (PID=20223) to work on /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T09:09:15.811+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/optum_ml_dag.py for tasks to queue
[2025-02-21T09:09:15.814+0000] {logging_mixin.py:188} INFO - [2025-02-21T09:09:15.813+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T09:09:16.842+0000] {logging_mixin.py:188} INFO - [2025-02-21T09:09:16.794+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/optum_ml_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/optum_ml_dag.py", line 7, in <module>
    from sklearn.ensemble import RandomForestClassifier
ModuleNotFoundError: No module named 'sklearn'
[2025-02-21T09:09:16.851+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/optum_ml_dag.py
[2025-02-21T09:09:16.949+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/optum_ml_dag.py took 1.153 seconds
